### DISCUSSION TITLE
Reg :- S3 support & capabilities for production system implementation

### DISCUSSION THREAD

**Discussion by RVaidhy** [openobserve/openobserve#1991] [General]
### Description

Hi Team, 

We are using AWS Cloud for our environment. 

At present we are using a single EC2 to collect the logs inside openobserve. Later this will be converted to HA.

Now the ask here is, how to store/ copy the same data (COPY of the same data that we are seeing it inside openobserve after  completing the things under functions + enrichment ) in to a S3. 

Or 

Is it like only we can feed the data from S3 to openobserve for process and not taking out the processed/enriched data out of it  for further process ? 

We need the enriched data out from the environment where we host openobserve system for various analytical purpose. Please clear this. 

Ref :-  
https://openobserve.ai/docs/storage/#disk

### Proposed solution

N/A

### Alternatives considered

N/A

**Comment by prabhatsharma** [comment]
ideally you should have used single node server with s3 as backend storage. That would have allowed you to use the data by external systems along with OpenObserve. OpenObserve will store all enriched data in s3 this way instead of on local disk of ec2 instance.

Moving from single node local storage to s3 backed storage is an involved activity. Please reach out to our team on slack if you want this, and we can help you with that.

**Reply by kenny8zeng** [reply]
I do have a requirement and seek assistance. I have provided S3 configuration for docker-compose but have not been successful in storing data on S3：

```
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.10.6
    restart: unless-stopped
    ports:
      - "5080:5080"
    volumes:
      - ${PWD}/data:/data
    environment:
      ZO_ROOT_USER_EMAIL: "admin@XXX.com"
      ZO_ROOT_USER_PASSWORD: "XXXXXXXXX"
      ZO_LOCAL_MODE_STORAGE: "s3"
      ZO_S3_PROVIDER: "aws"
      ZO_S3_REGION_NAME: "ap-southeast-1"
      ZO_S3_BUCKET_NAME: "phai-openobs"
      ZO_S3_ACCESS_KEY: "XXXXXXXXXXXX"
      ZO_S3_SECRET_KEY: "XXXXXXXXXXXXXXXXXXXX/nyNhVMyqpFX"
      ZO_S3_BUCKET_PREFIX: "hai/"
```
