### DISCUSSION TITLE
Clarification regarding 0.10.* breaking changes

### DISCUSSION THREAD

**Discussion by erkexzcx** [openobserve/openobserve#3310] [Q&A] [answered]
Here is the list of breaking changes, when upgrading from `0.9.*` to `0.10.*`: https://github.com/openobserve/openobserve/releases/tag/v0.10.0

Could you please clarify the following?

1. "_We only support MySQL and PostgreSQL as metadata store for cluster mode from this version_" - does it mean that ETCD is not supported for cluster mode? :eyes: 
2. "_We support both NATS and Etcd as cluster coordinator from this version_" - first time hearing about NATS. Is this some sort of integrated coordination system which can be used instead of ETCD? If I understand it correctly, NATS is internal coordination system that does not require external service (unlike ETCD)? If so, what are migration instructions?
3. "_If applications is running in cluster mode please scale all deployments to zero only use single compactor to upgrade_" - any guidance on how to "scale to zero"? I have 3 nodes cluster, would like to hear out how to do it, because I assume I only have to leave 1 node running, upgrade it, then upgrade and start other nodes?

**Comment by hengfeiyang** [comment]
1. etcd still need for cluster coordinator. we use MySQL / PostgreSQL to store metadata, like: users, alerts, dashboards
2. both support `etcd` and `NATS` if you don't familiar NATS you don't need migration to NATS, just keep using etcd. 
3. if you are running in kubernetes you will know how to scale, if not maybe you are running with binary, then you can simple stop the OpenObserve service. just leave one compactor node starting and upgrade this node to v0.10.0. after this node started and works, then we can change other nodes to v0.10.0 and start the node.

**Reply by erkexzcx** [reply]
Thank you.

> etcd still need for cluster coordinator. we use MySQL / PostgreSQL to store metadata, like: users, alerts, dashboards

Could you please confirm or deny - ETCD is no longer used for metadata and I **MUST** switch to MySQL/PostgreSQL? Or I misunderstood it and ETCD can still be used like its used with `0.9.*`?

**Reply by hengfeiyang** [reply, marked as answer]
Yes, You must setup MySQL / PostgreSQL for store metadata since v0.10.0. and you still need etcd for cluster, so, you need:
`etcd + MySQL` or `etcd + PostgreSQL` now, in 0.9.x you only need `etcd`.

**Comment by erkexzcx** [comment]
Hi @hengfeiyang. I've upgraded from `v0.9.1` to `v0.10.5` and OpenObserve seem to work just fine. Where is the catch? I am not using mysql/postgresql.. :thinking: 

```yaml
  openobserve-1:
    image: public.ecr.aws/zinclabs/openobserve:v0.10.5
    container_name: openobserve-1
    depends_on:
      - etcd
      - minio
      - mariadb
    environment:
      - ZO_LOCAL_MODE=false
      - ZO_INSTANCE_NAME=openobserve-1
      - ZO_ROOT_USER_EMAIL=test@test.test
      - ZO_ROOT_USER_PASSWORD=testtest
      - ZO_ETCD_ADDR=etcd:2379
      - ZO_S3_SERVER_URL=http://minio:9000
      - ZO_S3_REGION_NAME=us-east-1
      - ZO_S3_ACCESS_KEY=minio
      - ZO_S3_SECRET_KEY=miniopass123
      - ZO_S3_BUCKET_NAME=openobserve
      - ZO_S3_PROVIDER=minio
      - ZO_DATA_DIR=/var/lib/openobserve/
    volumes:
      - ./openobserve/1/data:/var/lib/openobserve
    restart: always
  openobserve-2:
    image: public.ecr.aws/zinclabs/openobserve:v0.10.5
    container_name: openobserve-2
    depends_on:
      - etcd
      - minio
      - mariadb
    environment:
      - ZO_LOCAL_MODE=false
      - ZO_INSTANCE_NAME=openobserve-2
      - ZO_ROOT_USER_EMAIL=test@test.test
      - ZO_ROOT_USER_PASSWORD=testtest
      - ZO_ETCD_ADDR=etcd:2379
      - ZO_S3_SERVER_URL=http://minio:9000
      - ZO_S3_REGION_NAME=us-east-1
      - ZO_S3_ACCESS_KEY=minio
      - ZO_S3_SECRET_KEY=miniopass123
      - ZO_S3_BUCKET_NAME=openobserve
      - ZO_S3_PROVIDER=minio
      - ZO_DATA_DIR=/var/lib/openobserve/
    volumes:
      - ./openobserve/2/data:/var/lib/openobserve
    restart: always
  openobserve-3:
    image: public.ecr.aws/zinclabs/openobserve:v0.10.5
    container_name: openobserve-3
    depends_on:
      - etcd
      - minio
      - mariadb
    environment:
      - ZO_LOCAL_MODE=false
      - ZO_INSTANCE_NAME=openobserve-3
      - ZO_ROOT_USER_EMAIL=test@test.test
      - ZO_ROOT_USER_PASSWORD=testtest
      - ZO_ETCD_ADDR=etcd:2379
      - ZO_S3_SERVER_URL=http://minio:9000
      - ZO_S3_REGION_NAME=us-east-1
      - ZO_S3_ACCESS_KEY=minio
      - ZO_S3_SECRET_KEY=miniopass123
      - ZO_S3_BUCKET_NAME=openobserve
      - ZO_S3_PROVIDER=minio
      - ZO_DATA_DIR=/var/lib/openobserve/
    volumes:
      - ./openobserve/3/data:/var/lib/openobserve
    restart: always
```
