### DISCUSSION TITLE
Invalid username or password

### DISCUSSION THREAD

**Discussion by APT256** [openobserve/openobserve#3321] [Q&A]
I just installed openobserve [Release v0.10.2-rc1](https://github.com/openobserve/openobserve/releases/tag/v0.10.2-rc1) on Ubuntu Server 22.04.4 LTS. The install was fine and the web page is available. I start OpenObserve with the command from the quick start guide: "ZO_ROOT_USER_EMAIL="root@example.com" ZO_ROOT_USER_PASSWORD="Complexpass#123" openobserve". When I enter root@example.com for the username and Complexpass#123 for the password, I keep getting  "Invalid username or password" errors. I have tried other email accounts and passwords, but nothing is accepted. 

How do I get logged in the first time to setup my admin account?

v/r
Jon

If it matters, I put the openobserve file in /opt/ with execute privs and added /opt to the system path.

**Comment by hengfeiyang** [comment]
it is just a binary file you can put it anywhere, and `ZO_ROOT_USER_EMAIL` and `ZO_ROOT_USER_PASSWORD` are two environment, you can use:
```
export ZO_ROOT_USER_EMAIL="mailto:root@example.com"
export ZO_ROOT_USER_PASSWORD="Complexpass#123"
```
it is same, if you can't login, try to delete the `./data/` directory in the same directory with `openobserve` binary and try again.

**Comment by APT256** [comment]
@hengfeiyang I tried this but still no luck. I think I am missing some files/folders. I am downloading the 
openobserve-v0.10.2-linux-amd64.tar.gz binary from github and expanding it in /opt/openobserve. This compressed file only has the openobserve binary. There are no other files/folders in the compressed file. I manually created a data directory and gave it 775 permissions root/users. I exported the environment variables and ran the binary. I then enter root@example.com and Complexpass#123 but I still get the invalid username or password error.

**Comment by jrouaix** [comment]
Same here, in a docker compose file

```yaml
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "dev@website.com"
      ZO_ROOT_USER_PASSWORD: "pa$$w0rd"
    ports:
      - "5080:5080"
```

Does not work : `Invalid username or password`
