### DISCUSSION TITLE
Security enhancement: OTEL collector env var, not hardcoded

### DISCUSSION THREAD

**Discussion by agardnerIT** [openobserve/openobserve#3850] [Ideas]
the "how to ingest" snippets contain a hardcoded Authorization header.

My worry is that someone would accidentally commit this to Git).

```
exporters:
  otlphttp/openobserve:
    endpoint: http://localhost:5080/api/default/
    headers:
      Authorization: Basic <REDACTED_VALUE_HERE>
      stream-name: default
```

Perhaps a better solution would be:

```
export OPEN_OBSERVE_AUTH_HEADER = <REDACTED_VALUE_HERE>

exporters:
  otlphttp/openobserve:
    endpoint: http://localhost:5080/api/default/
    headers:
      Authorization: Basic $OPEN_OBSERVE_AUTH_HEADER
      stream-name: default
```
