### DISCUSSION TITLE
Docker logs into OpenObserve?

### DISCUSSION THREAD

**Discussion by GD-Dal** [openobserve/openobserve#4622] [Q&A]
Hi
Is there a guide, or even a way, to send the docker logs (docker logs <container name> into OpenObserve?
I guess it will be as OO was a syslog server kind of.

Thanks

**Comment by hengfeiyang** [comment]
You can use fluent-bit or vector collect docker logs and send to o2.

**Comment by GD-Dal** [comment]
Thanks.
What about the Open Telemetry Collector? No good?

I'm struggling to format the data and transform them into meaningful dashboards, though.

**Reply by hengfeiyang** [reply]
otel collector also is great. just config it like this:
https://openobserve.ai/docs/ingestion/logs/otlp/

**Comment by GD-Dal** [comment]
Probably not a OO issue, but I'm getting permission denied when trying to read the docker log files:
`otel-collector  | 2024-10-14T14:33:33.033Z      warn    fileconsumer/file.go:47 finding files   {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "error": "no files match the configured criteria\nfind files with '/var/lib/docker/containers/*/*-json.log' pattern: open .: permission denied"}`

docker runs using a user called dockeruser, and both the user and docker group is added to sudoers
I have also tried to start the _docker compose using sudo docker compose up -d_, but same result

`receivers:
  filelog:
    include_file_path: true
    include:
      - /var/lib/docker/containers/*/*-json.log
    operators:
      - id: container-parser
        type: container

exporters:
  otlphttp/openobserve:
    endpoint: https://oo.domain.tld/api/default
    headers:
      Authorization: Basic YXBwX2Fsdfgdsagfhg0Ywd2tsTm5k
      stream-name: default`

`services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    #privileged: true
    #user: root
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - frontend
      - backend
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
networks:
  frontend:
    external: true
  backend:
    external: true`

Don't know why so simple things always needs to be so hard

**Reply by YashodhanJoshi1** [reply]
Hey can you try the following -
- change the receiver include as ` /var/lib/docker/containers/**/**-json.log` (double *)
- add a key in the service `user: "0"` so it will be like
```
services:
  test:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: testcontainer
    user: "0"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

```

This is still giving me errors like 
```
{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "/var/lib/docker/containers/31adfca9e6ced680058a5510f30fd0194cb2158adba75a118c1a014b0b731cc4/31adfca9e6ced680058a5510f30fd0194cb2158adba75a118c1a014b0b731cc4-json.log", "error": "failed to process the docker log: failed to detect a valid log path"}

```

But I think this is more related to how otel config is done. This should atleast solve the permission error.

**Comment by GD-Dal** [comment]
Thanks for answering.
I get the same error as you after configuring user 0, but I guess it's one step further

**Comment by YashodhanJoshi1** [comment]
Hey @GD-Dal , I managed to ingest docker logs into oo using the following receiver otel config :
```
filelog:
    include_file_path: true
    include:
      - /var/lib/docker/containers/**/**.log
    operators:
      - id: container-parser
        type: container
        add_metadata_from_filepath: false

```

Main addition is `add_metadata_from_filepath: false` . I think the issue is that the container parser was adding filepath as an object `{log:{file:path:...}}}` but the filelog receiver was expecting it in a string as `log.file.path` not sure if this is intentional or an upstream spec mismatch, but atleast for your case I think using above should solve it.

While the actual json logs are consumed in oo correctly, not sure if you're usecase needs to have the filepath processed. Please check once. Thanks!
