### DISCUSSION TITLE
Logs Not Appearing in OpenObserve When Sent from Spring Boot Application 3.4.0

### DISCUSSION THREAD

**Discussion by vaysagekv** [openobserve/openobserve#5317] [Q&A]
**Issue Description:**
I am experiencing an issue where logs sent from my Spring Boot 3.4.0 application are not appearing in OpenObserve. Both traces and metrics are being sent and received successfully, but logs are not visible in the OpenObserve interface.

**Environment Details:**

- Spring Boot Version: 3.4.0
- OpenObserve Endpoint: http://10.10.11.248:5080
- Dependencies Used:

```
<dependency>
    <groupId>io.micrometer</groupId>
    <artifactId>micrometer-registry-otlp</artifactId>
    <version>1.14.1</version>
</dependency>
<dependency>
    <groupId>io.opentelemetry</groupId>
    <artifactId>opentelemetry-exporter-otlp</artifactId>
</dependency>
<dependency>
    <groupId>io.micrometer</groupId>
    <artifactId>micrometer-tracing</artifactId>
    <version>1.4.0</version>
</dependency>
<dependency>
    <groupId>io.micrometer</groupId>
    <artifactId>micrometer-tracing-bridge-otel</artifactId>
    <version>1.4.0</version>
</dependency>
<dependency>
    <groupId>io.opentelemetry</groupId>
    <artifactId>opentelemetry-sdk-logs</artifactId>
    <version>1.44.1</version>
</dependency>
<dependency>
    <groupId>io.opentelemetry</groupId>
    <artifactId>opentelemetry-exporter-otlp-logs</artifactId>
    <version>1.26.0-alpha</version>
    <scope>runtime</scope>
</dependency>
```

**Application Configuration (application.yml):**

```
management: 
  otlp: 
    logging:
      compression: gzip
      transport: http
      connect-timeout: 1m
      timeout: 1m
      export:
        enabled: true
      headers: 
        enabled: true 
        Authorization: Basic *****
        organization: default
        stream-name: applogs
        Content-Type: application/json
      endpoint: http://10.10.11.248:5080/api/default/logs
    metrics: 
      export: 
        url: http://10.10.11.248:5080/api/default/v1/metrics
        enabled: true 
        step: 1m # Interval for pushing metrics 
        headers: 
          enabled: true 
          Authorization: Basic *****
          organization: default
          stream-name: default
          service: 
            name: default
    tracing: 
      export:
        enabled: true
      endpoint: http://10.10.11.248:5080/api/default/traces
      headers: 
        active : true
        enabled: true 
        step: 1m  
        Authorization: Basic *****
        organization: default
        stream-name: apptraces
        service: 
          name: default
```

**Observations**:
**Traces**: Successfully sent and visible in OpenObserve.
**Metrics**: Successfully sent and visible in OpenObserve.
**Logs**: Despite enabling log export and configuring the endpoint, logs are not visible in OpenObserve.

**Steps Taken to Troubleshoot:**
Verified that the logs are generated in the application.
Confirmed the OpenObserve endpoint is reachable from the application server.
Checked logs in the application for any export-related errors (none found).
Double-checked the stream-name and Authorization headers for correctness.

**Expected Behavior:**
Logs from the Spring Boot application should appear in the OpenObserve dashboard under the configured stream.

**Actual Behavior:**
Logs are not appearing in OpenObserve.

**Questions:**
Is there a specific configuration required in OpenObserve to enable log ingestion over OTLP?
Are the dependencies and versions I’m using correct for this setup?
Does OpenObserve support OTLP logs out of the box, or is additional configuration needed on the server side?

**Additional Context:**
I am using the OpenTelemetry OTLP exporter for logs.
Both traces and metrics are sent over the same endpoint structure and work fine, which indicates connectivity is not the issue.

**Request:**
Please provide guidance or highlight any misconfiguration. If additional information or logs are needed, I’ll be happy to provide them.

**Thank You!**
Thank you for your assistance and for building such a powerful observability tool.
