### DISCUSSION TITLE
Help Needed: 503 Service Unavailable on Redirect After GitHub SSO with Dex in Enterprise Mode

### DISCUSSION THREAD

**Discussion by L0d0c** [openobserve/openobserve#6306] [Q&A]
Hi everyone,

I'm encountering an issue when using Enterprise mode with Dex for SSO via GitHub. After a successful connection with GitHub, during the redirection phase the connector appears to disconnect and I receive a 503 Service Unavailable error.

Below is an anonymized version of my configuration for enabling Enterprise mode with Dex. I've replaced sensitive information such as domains, client IDs, and secrets with example values. The relevant snippet is:

```
enterprise:
  enabled: true
  dex:
    enabled: true
    parameters:
      O2_CALLBACK_URL: "https://cloud.example.com/web/cb" 
      O2_DEX_SCOPES: "openid profile email offline_access"
      O2_DEX_GROUP_ATTRIBUTE: "groups"
      O2_DEX_DEFAULT_ORG: default
      O2_DEX_DEFAULT_ROLE: user
      O2_DEX_ROLE_ATTRIBUTE: role
      O2_DEX_NATIVE_LOGIN_ENABLED: "true"
      O2_DEX_GROUP_CLAIM: "groups"
    config:
      issuer: "https://auth.example.com/dex"
      storage:
        type: kubernetes
        config:
          inCluster: true
      web:
        http: 0.0.0.0:5556
      frontend:
        issuer: "OpenObserve"
        logoURL: "https://cloud.openobserve.ai/web/src/assets/images/common/open_observe_logo.svg"
        theme: dark
      expiry:
        idTokens: 10m
        refreshTokens:
          validIfNotUsedFor: 30m
      staticClients:
        - id: "example-client"
          name: "example-client"
          redirectURIs:
            - "https://cloud.example.com/config/redirect"
          secret: "REDACTED_BASE64_SECRET"
      oauth2:
        responseTypes: [ "code" ]
        skipApprovalScreen: true
        alwaysShowLoginScreen: false
      connectors:
        - type: github
          id: github
          name: "GitHub"
          config:
            clientID: "YOUR_GITHUB_CLIENT_ID"
            clientSecret: "YOUR_GITHUB_CLIENT_SECRET"
            redirectURI: "https://auth.example.com/dex/callback"
    image:
      repository: dexidp/dex
      tag: v2.37.0
      pullPolicy: IfNotPresent
    extraEnv: []
    podAnnotations: {}
    ingress:
      enabled: true
      className: "cilium"
      annotations:
        "cert-manager.io/cluster-issuer": "ingress"
        "cert-manager.io/issuer": null
        "ingress.kubernetes.io/ingress-class": "cilium"
        "kubernetes.io/tls-acme": "false"
        "nginx.ingress.kubernetes.io/enable-cors": "false"
      hosts:
        - host: auth.example.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: dex-tls
          hosts:
            - auth.example.com
```
 
### Error Details:
During redirection (after a successful GitHub SSO connection), I receive the following error:

Request:
```
GET /config/redirect?code=REDACTED_CODE&state=REDACTED_STATE HTTP/1.1
Host: cloud.example.com
User-Agent: MY_USER_AGENT
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br, zstd
Referer: https://cloud.example.com/
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: cross-site
Sec-Fetch-User: ?1
Priority: u=0, i
```

Response:
```
Failed to connect to host: Internal error: connector has been disconnected : HTTP/1.1 503 Service Unavailable
vary: accept-encoding
content-encoding: br
date: Wed, 19 Mar 2025 00:28:51 GMT
x-envoy-upstream-service-time: 92
server: envoy
transfer-encoding: chunked
```
This error indicates that the connector is being disconnected during the redirection, resulting in a 503 response.

### What I've Tried/Considered:
- I have verified the configuration with GitHub in OAuth Apps mode, and it appears to work correctly.
- The OpenObserve application itself seems to function properly.
- OAuth authentication is working as expected.
- I suspect there might be an issue with the ingress configuration; however, when testing GitHub OAuth with Argo CD, it works perfectly.

Any guidance on how to resolve this issue or further debugging steps would be greatly appreciated. Thanks in advance for your help!
