### ISSUE TITLE
Document comparison to Elaasticsearch and Grafana

### ISSUE THREAD

**Issue by bck01215** [openobserve/openobserve#1450]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

It may be nice for users interested in OpenObserve

### Proposed solution

# Compare to other products

Today I used vector.dev to compare Loki, ElasticSearch, and OpenObserve through their free cloud offerings. Here is a summary of what I found.

Using the demo_logs for vector.dev I add three outputs.
```toml

[sources.demo]
type = "demo_logs"
count = 22_000_000
sequence = true
format = "apache_common"
interval = 0.0


[sinks.zinc]
inputs = ["demo"]
type = "http"
uri = "https://api.openobserve.ai/api/org/default/_json"
method = "post"
auth.strategy = "basic"
auth.user = "user@gmail.com"
auth.password = "pass"
compression = "gzip"
encoding.codec = "json"
encoding.timestamp_format = "rfc3339"
healthcheck.enabled = false


[sinks.elastic]
type = "elasticsearch"
inputs = ["demo"]
api_version = "auto"
doc_type = "_doc"
endpoints = ["https://test.es.us-central1.gcp.cloud.es.io"]
mode = "bulk"
bulk.action = "create"
bulk.index = "test2"
auth.user = "elastic"
auth.password = "pass"
auth.strategy = "basic"


[sinks.loki]
type = "loki"
inputs = ["demo"]
endpoint = "https://logsgrafana.net"
auth.strategy = "basic"
auth.password = "token"
auth.user = "user"
encoding.codec = "logfmt"
[sinks.loki.labels]
source = "vector"
```
## Size Comparison
 Solution|Loki|OpenObserve|ElasticSearch
---|---|---|---
Size|3.16GB|4.99GB|9.21GB
method|`sum(bytes_over_time({source="vector"} [range_test]))`|scan size|Stack management index size

A storage comparison showed OpenObserve (4.99GB) used roughly half of ElasticSearch (9.21GB) at 22 million docs.  The ElasticSearch index only had 4 fields.  A dataset with more fields would use more data and change the ratio. Loki used 3.16GB.

To get the ElasticSearch size, I used stack management to view the index. OpenObserve, I used the scan size. Loki I used `sum(bytes_over_time({source="vector"} [1h]))`. 1h was the length of my test submitting data.

## Speed Comparison

All tests taken were from the stats provided by the product.

### Bulk Results
Query times for a bulk result search looking for  text contains `meln1ks`: 

 Solution|Loki|OpenObserve|ElasticSearch
---|---|---|---
Speed|350ms/1600ms|926ms|1964ms

Note Loki is likely faster because it stops searching after 1k results and does not give a total match count. When increased to 5k (the max allowed), the query took 1.6s on the first search and reduced on subsequent. With 0 matches both ElasticSearch and OpenObserve were nearly instant. Loki took 10 seconds.

### Single Result
Query times for a bulk result search looking for  text contains `204.170.229.57`: 

 Solution|Loki|OpenObserve|ElasticSearch
---|---|---|---
Speed|8400ms|1116ms|2533ms

### Alternatives considered

N/A
