### ISSUE TITLE
Ingestion menu redesign (Add recommended and custom tabs)

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1668]
### Which OpenObserve functionalities are relevant/related to the feature request?

ingestion

### Description

We can provide simplified ingestion mechanism for multiple platforms using OTEL collector. 

### Proposed solution

We can revise the ingestion menu to have 2 tabs.

<img width="628" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/73030919-8c80-42ed-8ff5-098df94b42d6">

Details of each section are below:

#### 1. Kubernetes
 https://github.com/openobserve/openobserve-helm-chart/tree/main/charts/openobserve-collector
```shell
# install cert-manager
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.1/cert-manager.yaml

# install opentelemetry operator
kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml

# Wait for 2 minutes

# update helm repo
helm repo add openobserve https://charts.openobserve.ai
helm repo update

# create namespace
kubectl create ns openobserve-collector

# install openobserve collector
helm --namespace openobserve-collector -f values.yaml \
     install o1c openobserve/openobserve-collector \
     --set exporters."otlphttp/openobserve".endpoint=https://api.openobserve.ai/api/default/  \
     --set exporters."otlphttp/openobserve".headers.Authorization="Basic hdfkjhgsjkfgjksgfjgsdjfb="  \
     --set exporters."otlphttp/openobserve_k8s_events".endpoint=https://api.openobserve.ai/api/default/  \
     --set exporters."otlphttp/openobserve_k8s_events".headers.Authorization="Basic hdfkjhgsjkfgjksgfjgsdjfb="  
```

#### 2. Linux - https://github.com/openobserve/agents#linux

```shell
wget https://raw.githubusercontent.com/openobserve/agents/main/linux/install.sh \
     && chmod +x install.sh && sudo ./install.sh {URL} {authorization_token}
```

#### 3. Windows - https://github.com/openobserve/agents#windows

You need minimum PowerShell 6 to run the install script. you can check your PowerShell version by running `$PSVersionTable.PSVersion` in your terminal.

You should see something like this:

```powershell
PS C:\> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      3      7
```

Major should be at least 6.

You can download and install the latest version of powershell from [here](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows)

From powershell terminal:

```powershell
Invoke-WebRequest -Uri https://raw.githubusercontent.com/openobserve/agents/main/windows/install.ps1 -OutFile install.ps1 ; .\install.ps1 -URL <URL> -AUTH_KEY <Authorization_Key>
```

e.g.

```powershell
Invoke-WebRequest -Uri https://raw.githubusercontent.com/openobserve/agents/main/windows/install.ps1 -OutFile install.ps1 ; .\install.ps1 -URL https://localhost:5080/api/default -AUTH_KEY cm9vdEBowWjJSanhscWtSbVB5S0VE
```

#### 4. OTEL Collector:

**OTLP HTTP**

```yaml
exporters:
  otlphttp/openobserve:
    endpoint: https://api.openobserve.ai/api/default/
    headers:
      Authorization: Basic < base64 encoded auth >
      stream-name: default
  otlphttp/openobserve_k8s_events:
    endpoint: https://api.openobserve.ai/api/default/
    headers:
      Authorization: Basic < base64 encoded auth >
      stream-name: k8s_events
```

**OTLP gRPC** (Will be available in 0.7.1 - Not available in router in 0.7.0):
```yaml
exporters:
  otlp/openobserve:
      endpoint: localhost:5081
      headers:
        Authorization: "Basic gsguydgsuygdusgiufkdsnlkdfsjoi="
        organization: default
        stream-name: default
      tls:
        insecure: true
  otlp/openobserve_k8s_events:
      endpoint: localhost:5081
      headers:
        Authorization: "Basic gsguydgsuygdusgiufkdsnlkdfsjoi="
        organization: default
        stream-name: k8s_events
      tls:
        insecure: true
```

####  5. Traces

**OTLP HTTP**:
```yaml
endpoint: https://api.openobserve.ai/api/default/v1/traces
headers:
  Authorization: Basic < base64 encoded auth >
```

**OTLP GRPC** (Will be available in 0.7.1 - Not available in router in 0.7.0):
```yaml
endpoint: localhost:5081
headers:
  Authorization: "Basic gsguydgsuygdusgiufkdsnlkdfsjoi="
  organization: default
  stream-name: default
tls:
  insecure: true
```
