### ISSUE TITLE
Compactor using CPU limit as to decide no of threads to process log files

### ISSUE THREAD

**Issue by slice-sanjeevm** [openobserve/openobserve#2024]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

It's a bad practices to assign cpu limit to k8s pods. Compactor is not  respecting requested CPU and creating no of threads equal to cpu limit core/ node code(in case limit not assigned) and try to process num_of_cores *256 MB (default max file size)  and spiking allocated memory.

Few threads regarding CPU LIMIT :- 
https://home.robusta.dev/blog/stop-using-cpu-limits
https://twitter.com/thockin/status/1134193838841401345

### Proposed solution

It has to use CPU requests to determine the number of threads to process.

### Alternatives considered

None form my side

**Comment by hengfeiyang** [comment]
The cpu request limit commonly is very small, like:
```
    limits:
      cpu: "8"
      memory: "16Gi"
    requests:
      cpu: "2"
      memory: "4Gi"
```

Even someone configure the request is `500`, it means only half of cpu core, in our case we can't create half or only one thread for process files.

If you think the limit is too big, you can set the limit same to the request like:

```
    limits:
      cpu: "2"
      memory: "4Gi"
    requests:
      cpu: "2"
      memory: "4Gi"
```

Or you can configure `ZO_FILE_MOVE_THREAD_NUM=2` to control that. this ENV uses cpu num as the default values.

But if you use helm deploy this option also control the ingester move file to s3 threads. you should only apply `ZO_FILE_MOVE_THREAD_NUM=2` to compactor.
