### ISSUE TITLE
Ability to set custom Authorization token in development environment

### ISSUE THREAD

**Issue by Orholt** [openobserve/openobserve#2691]
### Which OpenObserve functionalities are relevant/related to the feature request?

ingestion

### Description

Sometimes I need to remove locally created docker volumes when I'm testing mine solution and I noticed that my Authorization token changes every time. 

Is there any possibility to make it so that I could provide authorization token by for ex. env variable? It mostly matters due to the fact that I also use nginx to append this token into any proxied request I make to open observe.

### Proposed solution

You could for example provide environment variables:
`IS_DEVELOPMENT` that could provide information if it's just test environment (True/False)
`DEV_TOKEN` (string) that could set constant token if `IS_DEVELOPMENT` is set to `True`

For example:
```yaml
  openobserve:
      volumes:
          - openobserve-data:/data
      environment:
          - ZO_DATA_DIR=/data
          - ZO_ROOT_USER_EMAIL=root@observe.com
          - ZO_ROOT_USER_PASSWORD=stringPassword
          - IS_DEVELOPMENT=True
          - DEV_TOKEN=SAY8IiDwwajzVtTSowx8ZqxDkRPr8Ed7cXU9P6b4Jgehyj
      ports:
          - 5080:5080
      image: public.ecr.aws/zinclabs/openobserve:v0.8.0
```

### Alternatives considered

As an alternative, I propose adding the following environmental variable:
`ALLOW_ANONYMOUS_LOGGING` (True/False) that will allow pushing logs without any authorization
