### ISSUE TITLE
docker compose startup error thread 'main' panicked at src/service/search/sql.rs:689:51:

### ISSUE THREAD

**Issue by FlashIvano** [openobserve/openobserve#2787]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

cat docker-compose.yaml

```yaml
version: '3'

services:      
  # openobserve service
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.8.2-rc4-amd64
    container_name: openobserve
    ports:
      - "5080:5080"
      - "5081:5081"
      - "15514:15514"
      - "15514:15514/udp"
    volumes:
      - /opt/compose/openobserve/data:/data
    #depends_on:
      #- etcd
    environment:
      ZO_DATA_DIR: /data
      ZO_HTTP_PORT: 5080
      ZO_GRPC_PORT: 5081
      ZO_TCP_PORT: 15514
      ZO_UDP_PORT: 15514
      ZO_ROOT_USER_EMAIL: userhere
      ZO_ROOT_USER_PASSWORD: "passwordhere"
      ZO_MEMORY_CACHE_MAX_SIZE: 4096
      RUST_BACKTRACE: full
      # ZO_WEB_URL:
      # ZO_BASE_URI:
    restart: none

```

### Please provide the exception or error you saw

```true
openobserve  | 2024-02-27T05:38:35.167901288+00:00 INFO openobserve: Starting OpenObserve v0.8.2-rc4    
openobserve  | 2024-02-27T05:38:35.167940577+00:00 INFO openobserve: System info: CPU cores 4, MEM total 31798 MB, Disk total 69 GB, free 59 GB    
openobserve  | 2024-02-27T05:38:35.168058943+00:00 INFO config::ider: init ider with machine_id: 0    
openobserve  | 2024-02-27T05:38:37.182853590+00:00 INFO openobserve::service::db::user: Start watching user    
openobserve  | 2024-02-27T05:38:37.183130575+00:00 INFO openobserve::service::db::user: Users Cached    
openobserve  | 2024-02-27T05:38:37.183393441+00:00 INFO openobserve::service::db::organization: Organization settings Cached    
openobserve  | 2024-02-27T05:38:37.184592117+00:00 INFO openobserve::service::db::functions: Start watching function    
openobserve  | 2024-02-27T05:38:37.184683100+00:00 INFO openobserve::service::db::schema: Start watching stream schema    
openobserve  | 2024-02-27T05:38:37.184693500+00:00 INFO openobserve::service::db::alerts::templates: Start watching alert templates    
openobserve  | 2024-02-27T05:38:37.184713957+00:00 INFO openobserve::service::db::alerts::destinations: Start watching alert destinations    
openobserve  | 2024-02-27T05:38:37.184720452+00:00 INFO openobserve::service::db::alerts::triggers: Start watching Triggers    
openobserve  | 2024-02-27T05:38:37.184726136+00:00 INFO openobserve::service::db::alerts: Start watching alerts    
openobserve  | 2024-02-27T05:38:37.184760466+00:00 INFO openobserve::service::db::organization: Start watching organization settings    
openobserve  | 2024-02-27T05:38:37.184780493+00:00 INFO openobserve::service::db::compact::retention: Start watching stream deleting    
openobserve  | 2024-02-27T05:38:37.184786241+00:00 INFO openobserve::service::db::metrics: Start watching prometheus cluster leader    
openobserve  | 2024-02-27T05:38:37.185862269+00:00 INFO openobserve::service::db::schema: Stream schemas Cached    
openobserve  | 2024-02-27T05:38:37.186056795+00:00 INFO openobserve::service::db::functions: Functions Cached    
openobserve  | 2024-02-27T05:38:37.186483017+00:00 INFO openobserve::service::db::metrics: Prometheus cluster leaders Cached    
openobserve  | 2024-02-27T05:38:37.186715932+00:00 INFO openobserve::service::db::alerts::templates: Alert templates Cached    
openobserve  | 2024-02-27T05:38:37.186889960+00:00 INFO openobserve::service::db::alerts::destinations: Alert destinations Cached    
openobserve  | 2024-02-27T05:38:37.187046987+00:00 INFO openobserve::service::db::alerts: Alerts Cached    
openobserve  | 2024-02-27T05:38:37.187193260+00:00 INFO openobserve::service::db::alerts::triggers: Triggers Cached    
openobserve  | 2024-02-27T05:38:37.187365464+00:00 INFO openobserve::service::db::syslog: SyslogRoutes Cached    
openobserve  | 2024-02-27T05:38:37.187658701+00:00 INFO openobserve::service::db::syslog: SyslogServer settings Cached    
openobserve  | 2024-02-27T05:38:37.291463486+00:00 INFO openobserve::job: Job initialization complete    
openobserve  | 2024-02-27T05:38:37.291498723+00:00 INFO openobserve::job::syslog_server: Starting TCP UDP server    
openobserve  | 2024-02-27T05:38:37.291646849+00:00 INFO openobserve::service::db::syslog: Start watching syslog routes    
openobserve  | 2024-02-27T05:38:37.291930896+00:00 INFO openobserve::service::db::syslog: Start watching SyslogServer settings    
openobserve  | 2024-02-27T05:38:37.292406336+00:00 INFO openobserve: starting gRPC server at 0.0.0.0:5081    
openobserve  | thread 'main' panicked at src/service/search/sql.rs:689:51:
openobserve  | called `Result::unwrap()` on an `Err` value: Syntax(
openobserve  | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
openobserve  | regex parse error:
openobserve  |     \b {"ip": .dst_addr })\b
openobserve  |         ^
openobserve  | error: repetition quantifier expects a valid decimal
openobserve  | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
openobserve  | )
openobserve  | stack backtrace:
openobserve  |    0:     0x5639a761298b - <unknown>
openobserve  |    1:     0x5639a4b4bf00 - <unknown>
openobserve  |    2:     0x5639a760c4e3 - <unknown>
openobserve  |    3:     0x5639a7612724 - <unknown>
openobserve  |    4:     0x5639a76141d0 - <unknown>
openobserve  |    5:     0x5639a7613eef - <unknown>
openobserve  |    6:     0x5639a76146ee - <unknown>
openobserve  |    7:     0x5639a76145f2 - <unknown>
openobserve  |    8:     0x5639a7612e86 - <unknown>
openobserve  |    9:     0x5639a7614360 - <unknown>
openobserve  |   10:     0x5639a3d14a75 - <unknown>
openobserve  |   11:     0x5639a3d14fc3 - <unknown>
openobserve  |   12:     0x5639a654391e - <unknown>
openobserve  |   13:     0x5639a69226ab - <unknown>
openobserve  |   14:     0x5639a690eea7 - <unknown>
openobserve  |   15:     0x5639a692d7db - <unknown>
openobserve  |   16:     0x5639a692c883 - <unknown>
openobserve  |   17:     0x5639a6899d44 - <unknown>
openobserve  |   18:     0x5639a6decb2e - <unknown>
openobserve  |   19:     0x5639a6dde51d - <unknown>
openobserve  |   20:     0x5639a6a9adf3 - <unknown>
openobserve  |   21:     0x5639a6a9e1ad - <unknown>
openobserve  |   22:     0x5639a7601d1a - <unknown>
openobserve  |   23:     0x5639a6df1335 - <unknown>
openobserve  |   24:     0x7f4248fbe24a - <unknown>
openobserve  |   25:     0x7f4248fbe305 - __libc_start_main
openobserve  |   26:     0x5639a3e3cf01 - <unknown>
openobserve  |   27:                0x0 - <unknown>
openobserve exited with code 101
```
```


### Please provide the version you discovered this bug in (check about page for version information)

```true
OS: Rocky Linux 9
```
