### ISSUE TITLE
docker compose start fail，but no error message

### ISSUE THREAD

**Issue by Meaningisuse** [openobserve/openobserve#3081]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

```
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "root@example.com"
      ZO_ROOT_USER_PASSWORD: "Complexpass#123"
    ports:
      - "5080:5080"
    volumes:
      - data:/data
volumes:
  data:
```
<img width="325" alt="image" src="https://github.com/openobserve/openobserve/assets/15310195/cf08b6f3-a12d-4d06-a5b6-b905e1a3ae80">

### Please provide a link to a minimal reproduction of the bug

latest

### Please provide the exception or error you saw

```true
Attaching to openobserve
openobserve exited with code 0
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
public.ecr.aws/zinclabs/openobserve:latest
os: ubuntu 22.04
docker: 26.0.0
```
