### ISSUE TITLE
Postgres config explanantion

### ISSUE THREAD

**Issue by BigWebstas** [openobserve/openobserve#3313]
### Describe the problem that you experienced

I am unsure on where this is set? the other ZO entries are env variables but i am confused on where to set the postgres enabled:false part
```
config:
  ZO_META_STORE: "postgres"
  ZO_META_POSTGRES_DSN: "postgres://postgres:12345678@localhost:5432/openobserve"

postgres:
  enabled: false # disable bundled PostgreSQL
```

### Enter the URL of the topic with the problem

https://openobserve.ai/docs/ha_deployment/
