### ISSUE TITLE
No"Organizations" menu for root user

### ISSUE THREAD

**Issue by PlkMarudny** [openobserve/openobserve#3507]
### Describe the problem that you experienced

I cannot see "Organizations" menu item for root user

### Describe what you were looking for in the documentation

How to create a new organization

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/openobserve/openobserve/assets/4361591/b975f6af-0c5b-42bb-8fa0-f8a2acc37aac)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Version
Commit Hash
Build Date

v0.10.5
30d06f180da82120f75eb08b702eeb0e10438470
2024-04-30T09:31:56Z
```

### Provide any additional information here in as much as detail as you can

```true
I am kind of confused, how to create a new organization in v0.10.5 (Docker image) 

Version
Commit Hash
Build Date

v0.10.5
30d06f180da82120f75eb08b702eeb0e10438470
2024-04-30T09:31:56Z
```

**Comment by gaby** [comment]
@PlkMarudny There's a workaround, when creating a User select "Other" in the organization dropdown then type the new Org name.

**Comment by PlkMarudny** [comment]
Well, "Users" is not visible either...

**Comment by gaby** [comment]
Isnt it the 4 icon from the bottom -> up ? @PlkMarudny

**Comment by PlkMarudny** [comment]
Yes, it is, there is no option of adding an user, however? Just search. And
"No data available icon with caption". Am I missing something here?

**Comment by PlkMarudny** [comment]
![image](https://github.com/openobserve/openobserve/assets/4361591/27fc29b1-2aec-422d-b82a-f62510c50d43)

**Comment by gaby** [comment]
Self-Hosted or Cloud? This is an option in self-hosted

**Comment by PlkMarudny** [comment]
Self hosted, latest available Docker image v0.10.5. Or should I try the RC
version?

**Comment by gaby** [comment]
I'm using v0.10.5 and I see it with Docker/Self-Hosted

**Comment by PlkMarudny** [comment]
Well, the only suspicious thing is a message in the console:
`Error while extracting fields`

**Comment by PlkMarudny** [comment]
![image](https://github.com/openobserve/openobserve/assets/4361591/f164f1b2-6a75-42e4-a430-180547787efb)

**Comment by prabhatsharma** [comment]
Try this - https://github.com/openobserve/openobserve/discussions/985

**Comment by PlkMarudny** [comment]
Well, removing all the data helped... **+ Add User** button reappeared.  However, after adding a new (admin) user with a new organization, root user cannot see this new organization.

**Comment by PlkMarudny** [comment]
Newly created user with a role "admin" can only add users with role "admin"...

**Comment by chreniuc** [comment]
I'm having the same problem, newly started container, with latest version, and there is no Organizations option. Also, I can only add adimn users and I can't see them after adding them

![Image](https://github.com/user-attachments/assets/5a697631-3315-4202-b5b1-67577da3ac92)

![Image](https://github.com/user-attachments/assets/ca9ceaf0-eb62-4827-b034-b25bd868722e)

![Image](https://github.com/user-attachments/assets/83dd6141-2334-4110-b121-8f4276a48587)

Docker compose:

```yml
version: "3"
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve
    restart: unless-stopped
    environment:
      # ZO_ROOT_USER_EMAIL: "admin@example.com"
      # ZO_ROOT_USER_PASSWORD: "Admin123"
      RUST_LOG: "trace"
    ports:
      - "5080:5080"
    volumes:
      - ./data:/data

```
