### ISSUE TITLE
openapi doc has error: SearchEventType not defined

### ISSUE THREAD

**Issue by shuaiyy** [openobserve/openobserve#3840]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

after upgrade from 0.10.0 to 0.10.8, the openapi doc become invalid!

I'm trying use [oapi-codegen](github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen) to gen a golang http client with openapi.json. 

when use 0.10.0, `StreamSettings.list.settings.partition_keys` is type `[]observe_sdk.StreamPartition`, but the body returns `partition_keys: {}`, not a list.

the 0.10.8 openapi.json is invalid,  gen sdk code failed!

openapi doc seems to be unreliable.

![image](https://github.com/openobserve/openobserve/assets/19821321/7c99a8dd-65c1-461c-9cca-4a51ffa7c33c)

### Please provide the version you discovered this bug in (check about page for version information)

```true
版本
提交ID
编译时间
v0.10.8-rc3
c0152b82ce32894ce0ed62ed2c90ca588bcd71de
2024-06-25T18:17:31Z

public.ecr.aws/zinclabs/openobserve:v0.10.8-rc3
```

### Anything else?

for codegen config.yaml：

```
# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: observe_sdk
output: sdk.gen.go
generate:
  models: true
  client: true
output-options:
  client-type-name: ObserveClient
  response-type-suffix: Resp
```

gen code:
`go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=config.yaml /tmp/openapi.json`
