### ISSUE TITLE
OpenTelemetry collector export unnecessary trailing slash

### ISSUE THREAD

**Issue by agardnerIT** [openobserve/openobserve#3849]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

No

### Description

```
otlphttp/openobserve:
    endpoint: http://localhost:5080/api/default/
    headers:
      Authorization: Basic ****
      stream-name: default
```

should be:

```
otlphttp/openobserve:
    endpoint: http://localhost:5080/api/default
    headers:
      Authorization: Basic ****
      stream-name: default
```

Notice I removed the trailing `/` on the `endpoint`.

When I do that, ingest works.

### Please provide the exception or error you saw

```true
{"kind": "exporter", "data_type": "logs", "name": "logging"}
2024-06-29T15:26:58.193+1000    error   exporterhelper/queued_retry.go:391      Exporting failed. The error is not retryable. Dropping data.{"kind": "exporter", "data_type": "logs", "name": "otlphttp/openobserve", "error": "Permanent error: error exporting items, request to http://localhost:5080/api/default//v1/logs responded with HTTP Status Code 404", "dropped_items": 1}
```
```


### Please provide the version you discovered this bug in (check about page for version information)

_No response_

### Anything else?

_No response_
