### ISSUE TITLE
Please show how to use vector.dev host_metrics with OpenObserve

### ISSUE THREAD

**Issue by neilmcguigan** [openobserve/openobserve#4024]
### Describe the problem that you experienced

Tried sending host metrics from vector to OpenObserve, but got errors

### Describe what you were looking for in the documentation

how to configure OpenObserver or vector to send/receive host metrics

**Comment by gaby** [comment]
@neilmcguigan Post your Vector config, this should work

**Comment by neilmcguigan** [comment]
@gaby

```

sources:

  host_metrics:
    type: host_metrics
    scrape_interval_secs: 60
    collectors:
      - cpu
      - filesystem
      - load
      - host
      - memory
      - network


sinks:

  openobserve_metrics:
    type: prometheus_remote_write
    inputs: [host_metrics]
    endpoint: http://localhost:5080/api/default/prometheus/api/v1/write
    auth:
      strategy: basic
      user: xxx@gmail.com
      password: CHANGE_ME
    compression: gzip
    healthcheck:
      enabled: false

```

**Comment by gaby** [comment]
@neilmcguigan What error are you getting and where? On vector or openobserve?

**Comment by neilmcguigan** [comment]
on vector, i get these errors:

`Jul 24 02:02:19 ip-10-0-5-166 vector[3034]: 2024-07-24T02:02:19.659676Z ERROR sink{component_kind="sink" component_id=openobserve_metrics component_type=prometheus_remote_write}:request{request_id=1}: vector::sinks::util::retries: Not retriable; dropping the request. reason="Http status: 400 Bad Request" internal_log_rate_limit=true`

`Jul 24 02:02:19 ip-10-0-5-166 vector[3034]: 2024-07-24T02:02:19.659729Z ERROR sink{component_kind="sink" component_id=openobserve_metrics component_type=prometheus_remote_write}:request{request_id=1}: vector_common::internal_event::service: Service call failed. No retries or retries exhausted. error=None request_id=1 error_type="request_failed" stage="sending" internal_log_rate_limit=true`

`Jul 24 02:02:19 ip-10-0-5-166 vector[3034]: 2024-07-24T02:02:19.659757Z ERROR sink{component_kind="sink" component_id=openobserve_metrics component_type=prometheus_remote_write}:request{request_id=1}: vector_common::internal_event::component_events_dropped: Events dropped intentional=false count=152 reason="Service call failed. No retries or retries exhausted." internal_log_rate_limit=true`

**Comment by gaby** [comment]
What does it say in OpenObserve? Are you using the username/token that OpenObserve gives you in the `Ingest` -> Metrics page?

**Comment by neilmcguigan** [comment]
@gaby OpenObserve provides no instructions on using Vector.Dev with Metrics, hence my request...

Please note that logging works fine

**Comment by neilmcguigan** [comment]
@gaby actually, if i send vector host **metrics** to the openobserve **log** endpoint, i can see them (as logs)

i guess i need to know the **metric** endpoint that works w vector

**Comment by gaby** [comment]
@neilmcguigan Copy the vector config that it gives you for logs and change the URL to the one for prometheus remote write.

**Comment by neilmcguigan** [comment]
why would that work? (it doesn't)

either way, I'd really like to use Vector (and OpenObserve should encourage its use too, as it's Rust and VRL)

however, I don't see a way to do so for metrics at this time, so I guess I'll use OTEL instead

**Comment by gaby** [comment]
I know what your problem is... Remove the `compression: gzip`

> @gaby
> 
> ```
> 
> sources:
> 
>   host_metrics:
>     type: host_metrics
>     scrape_interval_secs: 60
>     collectors:
>       - cpu
>       - filesystem
>       - load
>       - host
>       - memory
>       - network
> 
> 
> sinks:
> 
>   openobserve_metrics:
>     type: prometheus_remote_write
>     inputs: [host_metrics]
>     endpoint: http://localhost:5080/api/default/prometheus/api/v1/write
>     auth:
>       strategy: basic
>       user: xxx@gmail.com
>       password: CHANGE_ME
>     compression: gzip
>     healthcheck:
>       enabled: false
> ```

**Comment by gaby** [comment]
In reality you should be using `compression: snappy`. As stated here: https://prometheus.io/docs/specs/remote_write_spec/#protocol

**Comment by neilmcguigan** [comment]
nope, same prob. thanks anyways

**Comment by gaby** [comment]
The logs in OpenObserve should be telling you why the request is bad `http 400`.

**Comment by mridang** [comment]
@gaby that was it. What a rabbit hole. That fixed it.

**Comment by leeveeqee** [comment]
It works fine for me.

```
openobserve:
    type: "prometheus_remote_write"
    inputs: ["my_windows_metrics"]
    endpoint: "http://xxx:5080/api/default/prometheus/api/v1/write"
    healthcheck:
      enabled: false
    batch:
      max_events: 100
      timeout_secs: 5
    auth:
      strategy: "basic"
      user: "xxxx"
      password: 'xxxx'
```
