### ISSUE TITLE
Ingester continues using more memory until new inputs are stopped with MemoryTableOverflowError

### ISSUE THREAD

**Issue by bh-tt** [openobserve/openobserve#4284]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

No

### Description

We are evaluating openobserve as a graylog replacement in our infrastructure. Deployment on kubernetes (HA with s3 storage) worked fine, logs were being ingested, and then slowly the ingester memory climbs to its limit, at which point it errors on all new _multi ingest http calls with a MemoryTableOverflowError 400 status. Increasing the memory means this process takes longer, but even with 16G of memory (with about 750 json msg/s, averaging at 1.2 MB/s of data) the memory fills up in approx 20 minutes. If I calculate that right (1.2 MB/s * 1200s = 14.5 GB) this seems to mean the ingester keeps all messages in memory.

While the ingestion was ingesting normally I also ran some searches, interestingly these did not return any of the new data ingested until I restarted the ingester (so it seems the ingester does write the data when it exits normally).

All messages go into the same org and stream, of the logs type.

The docs say the max file size in memory should be `ZO_MAX_FILE_SIZE_IN_MEMORY`, which I checked to be equal to the default value of 256.

If you need more information I'll be happy to provide it.

### Please provide a link to a minimal reproduction of the bug

see helm chart values below

### Please provide the exception or error you saw

```true
ERROR openobserve::handler::http::request::logs::ingest: Error processing request default/default: MemoryTableOverflowError
INFO actix_web::middleware::logger: 127.0.0.6 "POST /api/default/default/_multi HTTP/1.1" 400 67 "-" "-" "Go-http-client/1.1" 0.000382
```
```


### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.10.8
8e51607ddeead104a5de98447ec1297851f67947
2024-07-25T04:10:44Z
```

### Anything else?

Chart values used to install:
```
    chart_version: 0.10.50
    values:
      ingester:
        persistence:
          storageClass: ceph-block-hdd
      nats:
        config:
          jetstream:
            fileStore:
              storageClassName: ceph-block-hdd
      config:
        ZO_S3_SERVER_URL: "http://{{ bucket_host }}:{{ bucket_port }}"
        ZO_S3_BUCKET_NAME: "{{ bucket_name }}"
        ZO_S3_PROVIDER: s3
        ZO_S3_REGION_NAME: ghg
        ZO_TELEMETRY: "false"
        ZO_COMPACT_DATA_RETENTION_DAYS: "15"
        ZO_COLUMN_TIMESTAMP: _timestamp
        # kube apiserver audit logs results in a lot of columns
        ZO_COLS_PER_RECORD_LIMIT: "1000"
        # fix for compactor memory usage bloom, see https://github.com/openobserve/openobserve/issues/3335
        ZO_BLOOM_FILTER_ON_ALL_FIELDS: false
      extraEnv:
        - name: ZO_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ o2_instance }}-bucket"
              key: AWS_SECRET_ACCESS_KEY
        - name: ZO_S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ o2_instance }}-bucket"
              key: AWS_ACCESS_KEY_ID
        - name: ZO_ROOT_USER_EMAIL
          value: root@example.com
        - name: ZO_ROOT_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ o2_instance }}-password"
              key: ROOT_USER_PASSWORD
      resources:
        ingester:
          requests:
            cpu: 500m
            memory: 4Gi
          limits:
            cpu: 2
            memory: 16Gi
        querier:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            memory: 2Gi
        compactor:
          requests:
            cpu: 10m
            memory: 1Gi
          limits:
            memory: 2Gi
        router:
          requests:
            cpu: 10m
            memory: 512Mi
          limits:
            memory: 2Gi
      podAnnotations:
        fluentbit.io/exclude: "true"
      postgres:
        enabled: true
        storage:
          storageClass: ceph-block-ssd
        pgadmin:
          enabled: false
```
