### ISSUE TITLE
how to work with ilogtail (alibaba)

### ISSUE THREAD

**Issue by KnightBlood** [openobserve/openobserve#4649]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

how to work with ilogtail (alibaba)
[](https://github.com/alibaba/ilogtail)

### Proposed solution

work with ilogtail

### Alternatives considered

work with ilogtail

**Comment by hengfeiyang** [comment]
the configure is same to others.

You can use:
https://ilogtail.gitbook.io/ilogtail-docs/plugins/flusher/flusher-otlp
or
https://ilogtail.gitbook.io/ilogtail-docs/plugins/flusher/flusher-http

this is an example from their document:
```
enable: true
inputs:
  - Type: service_docker_stdout
    Stderr: true
    Stdout: true
processors:
  - Type: processor_json
    SourceKey: content
    KeepSource: true
    ExpandDepth: 1
    ExpandConnector: ""
    KeepSourceIfParseError: true
flushers:
  - Type: flusher_http
    RemoteURL: http://localhsot:5080/api/default/default/_json
    Headers:
      Authorization: "Basic xxxxxxxxxxxxxxxxxxxx"
    QueueCapacity: 64
    Convert:
      Protocol: jsonline
      Encoding: json
```

But in there document they didn't introduce what is the different of `jsonline` and `custom_single`, you can have a try.
