### ISSUE TITLE
S3 not working

### ISSUE THREAD

**Issue by 90aca** [openobserve/openobserve#5066]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

It's currently not possible to connect OpenObserve to S3. This is my configuration:

```yaml
services:
  caddy:
    image: caddy:2.8.4-alpine
    volumes:
      - caddy:/data
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    environment:
      ZO_ROOT_USER_EMAIL: ${OPENOBSERVE_EMAIL}
      ZO_ROOT_USER_PASSWORD: ${OPENOBSERVE_PASSWORD}
      ZO_COMPACT_DATA_RETENTION_DAYS: 180
      ZO_LOCAL_MODE_STORAGE: s3
      ZO_S3_PROVIDER: minio
      ZO_S3_SERVER_URL: ${OPENOBSERVE_S3_SERVER_URL}
      ZO_S3_REGION_NAME: ${OPENOBSERVE_S3_REGION_NAME}
      ZO_S3_ACCESS_KEY: ${OPENOBSERVE_S3_ACCESS_KEY}
      ZO_S3_SECRET_KEY: ${OPENOBSERVE_S3_SECRET_KEY}
      ZO_S3_BUCKET_NAME: ${OPENOBSERVE_S3_BUCKET_NAME}
    volumes:
      - openobserve:/data
    restart: always

volumes:
  # used to store certificates and other
  caddy:
  # used to store metadata
  # https://openobserve.ai/docs/storage/
  openobserve:

configs:
  Caddyfile:
    content: |
      ${CADDY_DOMAIN} {
          reverse_proxy http://openobserve:5080
      }
```

And the .env file
```
OPENOBSERVE_EMAIL=XXX@XXX.XX
OPENOBSERVE_PASSWORD=XXX
OPENOBSERVE_S3_SERVER_URL=https://fsn1.your-objectstorage.com # using hetzner s3
OPENOBSERVE_S3_REGION_NAME=eu-central
OPENOBSERVE_S3_ACCESS_KEY=XXX
OPENOBSERVE_S3_SECRET_KEY=XXX
OPENOBSERVE_S3_BUCKET_NAME=XXX
CADDY_DOMAIN=XXX.XX
```

I have also tried using s3, instead of minIO, but without success. There are zero warnings or error manages in the logs, so I can't debug it.

### Please provide the exception or error you saw

```true
openobserve-1  | 2024-11-14T10:54:02.166868180+00:00 INFO openobserve: Starting OpenObserve v0.13.0    
openobserve-1  | 2024-11-14T10:54:02.167020659+00:00 INFO openobserve: System info: CPU cores 2, MEM total 3820 MB, Disk total 37 GB, free 32 GB    
openobserve-1  | 2024-11-14T10:54:02.168147736+00:00 INFO config::ider: init ider with machine_id: 0    
openobserve-1  | 2024-11-14T10:54:02.175800648+00:00 INFO infra::cache::file_data::disk: Loading disk cache start    
openobserve-1  | 2024-11-14T10:54:02.176982501+00:00 INFO infra::cache::file_data::disk: Loading disk cache done, total files: 0     
openobserve-1  | 2024-11-14T10:54:05.248534402+00:00 WARN ingester::wal: starting replay wal file: "./data/openobserve/wal/logs/0/XXXX-XXXX/logs/1731580996324887.wal"    
openobserve-1  | 2024-11-14T10:54:05.273578122+00:00 WARN ingester::wal: replay wal file: "./data/openobserve/wal/logs/0/XXXX-XXXX/logs/1731580996324887.wal", entries: 69, records: 531    
openobserve-1  | 2024-11-14T10:54:05.273705688+00:00 WARN ingester::wal: starting replay wal file: "./data/openobserve/wal/logs/0/XXXX-XXXX/metrics/1731580997442960.wal"    
openobserve-1  | 2024-11-14T10:54:05.337503779+00:00 WARN ingester::wal: replay wal file: "./data/openobserve/wal/logs/0/XXXX-XXXX/metrics/1731580997442960.wal", entries: 1000, records: 12003    
openobserve-1  | 2024-11-14T10:54:05.379132856+00:00 WARN ingester::wal: replay wal file: "./data/openobserve/wal/logs/0/XXXX-XXXX/metrics/1731580997442960.wal", entries: 1605, records: 18757    
openobserve-1  | 2024-11-14T10:54:05.379989964+00:00 INFO openobserve::service::db::user: Start watching user    
openobserve-1  | 2024-11-14T10:54:05.380166867+00:00 INFO openobserve::service::db::user: Users Cached    
openobserve-1  | 2024-11-14T10:54:05.380506366+00:00 INFO openobserve::service::db::organization: Organization settings Cached    
openobserve-1  | 2024-11-14T10:54:05.381374008+00:00 INFO openobserve::service::db::short_url: [SHORT_URLS] Cached with len: 0    
openobserve-1  | 2024-11-14T10:54:05.382690621+00:00 INFO openobserve::service::db::alerts::templates: Start watching alert templates    
openobserve-1  | 2024-11-14T10:54:05.382739072+00:00 INFO openobserve::service::db::short_url: Start watching short URLs    
openobserve-1  | 2024-11-14T10:54:05.382802078+00:00 INFO openobserve::service::db::schema: Start watching stream schema    
openobserve-1  | 2024-11-14T10:54:05.382819689+00:00 INFO openobserve::service::db::functions: Start watching function    
openobserve-1  | 2024-11-14T10:54:05.382827527+00:00 INFO openobserve::service::db::compact::retention: Start watching stream deleting    
openobserve-1  | 2024-11-14T10:54:05.382848279+00:00 INFO openobserve::service::db::metrics: Start watching prometheus cluster leader    
openobserve-1  | 2024-11-14T10:54:05.382867995+00:00 INFO openobserve::service::db::alerts::destinations: Start watching alert destinations    
openobserve-1  | 2024-11-14T10:54:05.382880193+00:00 INFO openobserve::service::db::pipelines: Start watching pipeline    
openobserve-1  | 2024-11-14T10:54:05.382890991+00:00 INFO openobserve::service::db::alerts::realtime_triggers: Start watching alert realtime triggers    
openobserve-1  | 2024-11-14T10:54:05.382905176+00:00 INFO openobserve::service::db::alerts::alert: Start watching alerts    
openobserve-1  | 2024-11-14T10:54:05.382921969+00:00 INFO openobserve::service::db::dashboards::reports: Start watching reports    
openobserve-1  | 2024-11-14T10:54:05.382932536+00:00 INFO openobserve::service::db::organization: Start watching organization settings    
openobserve-1  | 2024-11-14T10:54:05.384189616+00:00 INFO openobserve::service::db::short_url: [SHORT_URLS] Garbage collection start with cache size: 0    
openobserve-1  | 2024-11-14T10:54:05.385537548+00:00 INFO openobserve::service::db::short_url: [SHORT_URLS] Garbage collection end with cache size: 0    
openobserve-1  | 2024-11-14T10:54:05.396585549+00:00 INFO openobserve::service::db::schema: Stream schemas Cached    
openobserve-1  | 2024-11-14T10:54:05.396920157+00:00 INFO openobserve::service::db::functions: Functions Cached    
openobserve-1  | 2024-11-14T10:54:05.398269049+00:00 INFO openobserve::service::db::metrics: Prometheus cluster leaders Cached    
openobserve-1  | 2024-11-14T10:54:05.398512819+00:00 INFO openobserve::service::db::alerts::templates: Alert templates Cached    
openobserve-1  | 2024-11-14T10:54:05.398802341+00:00 INFO openobserve::service::db::alerts::destinations: Alert destinations Cached    
openobserve-1  | 2024-11-14T10:54:05.399168509+00:00 INFO openobserve::service::db::alerts::realtime_triggers: Alert realtime triggers Cached    
openobserve-1  | 2024-11-14T10:54:05.399510443+00:00 INFO openobserve::service::db::alerts::alert: Alerts Cached    
openobserve-1  | 2024-11-14T10:54:05.399744686+00:00 INFO openobserve::service::db::dashboards::reports: Reports Cached    
openobserve-1  | 2024-11-14T10:54:05.399991357+00:00 INFO openobserve::service::db::syslog: SyslogRoutes Cached    
openobserve-1  | 2024-11-14T10:54:05.400374564+00:00 INFO openobserve::service::db::syslog: SyslogServer settings Cached    
openobserve-1  | 2024-11-14T10:54:05.400553755+00:00 INFO openobserve::service::db::pipelines: Pipelines Cached    
openobserve-1  | 2024-11-14T10:54:05.400943740+00:00 INFO openobserve::job: Job initialization complete    
openobserve-1  | 2024-11-14T10:54:05.401067855+00:00 INFO openobserve: backend job init success    
openobserve-1  | 2024-11-14T10:54:05.401283597+00:00 INFO openobserve::job::alert_manager: Spawning embedded report server false    
openobserve-1  | 2024-11-14T10:54:05.401370762+00:00 INFO openobserve::service::db::syslog: Start watching syslog routes    
openobserve-1  | 2024-11-14T10:54:05.401490847+00:00 INFO openobserve::service::db::syslog: Start watching SyslogServer settings    
openobserve-1  | 2024-11-14T10:54:05.403025075+00:00 INFO openobserve: starting gRPC server at 0.0.0.0:5081    
openobserve-1  | 2024-11-14T10:54:05.403528862+00:00 INFO openobserve::job::compactor: [COMPACTOR] start run_compactor_pending_jobs_metric job    
openobserve-1  | 2024-11-14T10:54:05.403824342+00:00 INFO openobserve::service::db::schema: EnrichmentTables Cached    
openobserve-1  | 2024-11-14T10:54:05.405150875+00:00 INFO actix_server::builder: starting 2 workers
openobserve-1  | 2024-11-14T10:54:05.405195790+00:00 INFO actix_server::server: Tokio runtime found; starting in existing Tokio runtime
openobserve-1  | 2024-11-14T10:54:05.405202797+00:00 INFO actix_server::server: starting service: "actix-web-service-0.0.0.0:5080", workers: 2, listening on: 0.0.0.0:5080
openobserve-1  | 2024-11-14T10:54:05.407202167+00:00 INFO openobserve: starting HTTP server at: 0.0.0.0:5080, thread_id: 0    
openobserve-1  | 2024-11-14T10:54:05.446098765+00:00 INFO openobserve::common::meta::telemetry: sending event OpenObserve - Starting server    
openobserve-1  | 2024-11-14T10:54:05.469741658+00:00 INFO openobserve: starting HTTP server at: 0.0.0.0:5080, thread_id: 0    
openobserve-1  | 2024-11-14T10:54:05.569198993+00:00 INFO ingester::writer: [INGESTER:MEM] create file: ./data/openobserve/wal/logs/0/XXXX-XXXX/metrics/1731581645569183.wal    
openobserve-1  | 2024-11-14T10:54:05.576387036+00:00 INFO actix_web::middleware::logger: 172.18.0.3 "POST /api/XXXX-XXXX/prometheus/api/v1/write HTTP/1.1" 200 0 "10694" "-" "Vector/0.36.0 (x86_64-unknown-linux-musl a5e48bb 2024-02-13 14:43:11.911392615)" 0.032086    
openobserve-1  | 2024-11-14T10:54:05.687977800+00:00 INFO actix_web::middleware::logger: 172.18.0.3 "POST /api/XXXX-XXXX/prometheus/api/v1/write HTTP/1.1" 200 0 "28862" "-" "Vector/0.36.0 (x86_64-unknown-linux-musl a5e48bb 2024-02-13 14:43:11.911392615)" 0.044398
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.13.0
Commit Hash: eeecb3f1305ca6cccf7fdae06930438ebbe92cc1
Build Date: 2024-10-29T03:55:58Z
```
