### ISSUE TITLE
is oauth2 / oidc possible or not ?

### ISSUE THREAD

**Issue by cbueche** [openobserve/openobserve#5373]
### Describe the problem that you experienced

In [the doc](https://openobserve.ai/docs/SSO/), there is a TODO mention of OAuth2 and Github authentication/SSO. Questions:

- is this implemented and just missing doc ?
- Or is there a plan to implement it ?

### Enter the URL of the topic with the problem

https://openobserve.ai/docs/SSO/

### Describe what you were looking for in the documentation

how to configure oauth2 in the opensource version of openobserve.

### Describe the actions that led you to experience the problem

I tried to implement it but found no evidence of oauth2 in the code.

**Comment by prabhatsharma** [comment]
You can use the enterprise version of OpenObserve to enable it. Set this to true https://github.com/openobserve/openobserve-helm-chart/blob/8fb6fdd69bb10014be1847fd2d288a4b2c4906f1/charts/openobserve/values.yaml#L706 and configure appropriately and you will be up and running.

If you are ingesting under 200 GB of data every day there is no licensing cost for OpenObserve. Read this blog for further reference - https://openobserve.ai/blog/sso-tax

**Comment by cbueche** [comment]
interesting approach, thank you, my customer is now considering the enterprise version. I suggest adding a small message in the [doc](https://openobserve.ai/docs/SSO/) so other people do not spend hours on trying to enable something that doesn't exists.

**Comment by cbueche** [comment]
I'm trying to follow your guide: I first upgraded to v0.13.1, then v0.14.0. I set `ENTERPRISE_MODE = true` in my environment file (I run a standalone linux binary). I restarted OO, but I cannot see wheter I'm running Enterprise or free. Any hint on how to check this ?

The next question relates to Dex. Do I need to install dex and run it as separate package ? Or is dex integrated into OO and I only need to set it up ?

In the [doc](https://openobserve.ai/docs/SSO/), a `values.yaml` is populated, but how do I set these variables using environment ?

**Comment by Manazsharma** [comment]
Hi, first to be clear right now you are running O2 as a single node?

**Comment by cbueche** [comment]
> Hi, first to be clear right now you are running O2 as a single node?

yes, I deploy the binary on a single Linux server, along with a systemd file, which set my environment variables, and I start it. I feed data using fluent-bit.

**Comment by Manazsharma** [comment]
To check if Enterprise is enabled, you can go to **Management**, where you can find **Enterprise Settings**. (See below)
- ![Screenshot 2025-01-09 at 7 39 39 PM](https://github.com/user-attachments/assets/65c984ae-30a7-4c8e-8c49-62e920d4bf66)


Also for your next ques, dex is already integrated with O2 Binary and to **enable dex using environment** use: https://openobserve.ai/docs/environment-variables/#dex

**Comment by Manazsharma** [comment]
Hi @cbueche, can you do K8's? then you can deploy openobserve in High Availability (HA) mode. We have Terraform too, simplifying the complete setup- enabling, configuring dex for sso.

**Comment by cbueche** [comment]
> Hi @cbueche, can you do K8's? then you can deploy openobserve in High Availability (HA) mode. We have Terraform too, simplifying the complete setup- enabling, configuring dex for sso.

no, I cannot do k8s or docker. It has to be native.

**Comment by cbueche** [comment]
> To check if Enterprise is enabled, you can go to **Management**, where you can find **Enterprise Settings**. (See below)

ok so I found out I'm *not* in enterprise mode. What environment variable do I need ? I tried those :
```
ENTERPRISE_MODE = true
ENTERPRISE = true
```

**Comment by chaitanya-sistla** [comment]
Hello @cbueche please try `ENTERPRISE = true `

**Comment by cbueche** [comment]
> `ENTERPRISE = true`

I tried, with restart and re-login, no effect, I still do not get the "Enterprise Settings" mentioned by @Manazsharma.

**Comment by chaitanya-sistla** [comment]
@cbueche Just to confirm while enterprise can be configured, we do not have DEX and OpenFGA as part of it. But if you setup them as different containers then you can connect to them.

**Comment by cbueche** [comment]
> @cbueche Just to confirm while enterprise can be configured, we do not have DEX and OpenFGA as part of it. But if you setup them as different containers then you can connect to them.

oh now it's somewhat more clear, the doc is unclear to me. Anyway without enterprise mode, no DEX.

**Comment by Manazsharma** [comment]
Hi @cbueche, There was a little misunderstanding on my part in understanding your query, let me clarify here:
We do not provide binaries of Enterprise version, only for the open source version for now. Enterprise version can be run only using containers today. That will change in future.
You can find Docker images for enterprise here in case required: https://gallery.ecr.aws/zinclabs/openobserve-enterprise

**Comment by cbueche** [comment]
ok thanks for the clarification. I will check the requirement with my customer to decide on the strategy. It would be cool to have a working example of O2 and Dex with docker-compose.

**Comment by Manazsharma** [comment]
Cool, I can write a blog piece on this and keep you posted.

**Comment by cbueche** [comment]
that would be cool !

**Comment by cbueche** [comment]
I now have Openobserve Enterprise (container version) v0.14.1 running. Any hints for for connecting to Microsoft Entra is welcome :-)

**Comment by chaitanya-sistla** [comment]
Were you able to setup dex as an independent container? I can share the details of registered app in azure for SSO. Could you verify if the dex connection is successful?

**Comment by cbueche** [comment]
ok I wasn't even certain I need Dex between O2 and Entra. I will create a container for it.

**Comment by cbueche** [comment]
I have got dex almost running in container. Now I need to get proper config from my customer's Entra setup. Thanks for the help.

**Comment by chaitanya-sistla** [comment]
Wonderful. I will send you the instructions to create an OIDC in Azure along with connector details from a values.yaml. 

As I have all the screenshots there. What could be the best email?

**Comment by chaitanya-sistla** [comment]
Or allow me sometime, let me do it here so everyone else can find it helpful.

**Comment by cbueche** [comment]
great idea, no hurry

**Comment by elightcap** [comment]
@chaitanya-sistla were you able to get a working connection between dex and o2? From what i can tell, dex is set up properly, but it doesnt seem like o2 is calling it for auth

**Comment by chaitanya-sistla** [comment]
Hello @elightcap i wrote a blog today that is focused more on values.yaml from K8s but you can use similar to set as environment variables. 

https://openobserve.ai/blog/how-to-configure-sso-using-azure-oidc

**Comment by chaitanya-sistla** [comment]
Also did you set enterprise: true ?

**Comment by elightcap** [comment]
i think i did, but i just cant get that SSO button to show.

docker-compose.yml
```
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve-enterprise:latest
    container_name: openobserve
    restart: unless-stopped
    environment:
      enterprise.enabled: true
      config.O2_DEX_ENABLED: true
      O2_DEX_CLIENT_ID: "o2-client" # Client id of static client
      O2_DEX_CLIENT_SECRET: "base 64 encoded secret"   # This should be base64 encoded value of client secret 
      O2_DEX_BASE_URL: "https://dex.example.com/dex"    # URL of the Dex identity provider
      O2_DEX_REDIRECT_URL: "https://o2.example.com/config/callback"    # Should match to redirect uri specified in dex
      O2_CALLBACK_URL: "https://o2.example.com/web/cb" # after sucessful token received from dex, user will be redirected to this page
      O2_DEX_SCOPES: "openid profile email groups offline_access"   # scopes to be fetched from dex
      O2_DEX_GROUP_ATTRIBUTE: "css"  # Maps user to OpenObserve organization.
      O2_DEX_ROLE_ATTRIBUTE: "cn"   # User's role in the organization.
      O2_DEX_DEFAULT_ORG: "default" # Default organization for users not belonging to any group in ldap
    ports:
      - "5080:5080"
    volumes:
      - data1:/data
  dex:
    image: dexidp/dex:latest
    container_name: dex
    restart: unless-stopped
    ports:
      - "5556:5556"
    volumes:
      - ./dex/config.docker.yaml:/etc/dex/config.docker.yaml
```
config.docker.yaml
```
issuer: http://dex.example.com/dex
staticClients:
    - id: o2-client
      secret: dex client secret
      name: o2-client
      redirectURIs:
        - 'https://o2.example.com/config/callback'
storage:
  type: sqlite3
  config:
    file: {{ getenv "DEX_STORAGE_SQLITE3_CONFIG_FILE" "/var/dex/dex.db" }}

web:
{{- if getenv "DEX_WEB_HTTPS" "" }}
  https: {{ .Env.DEX_WEB_HTTPS }}
  tlsKey: {{ getenv "DEX_WEB_TLS_KEY" | required "$DEX_WEB_TLS_KEY in case of web.https is enabled" }}
  tlsCert: {{ getenv "DEX_WEB_TLS_CERT" | required "$DEX_WEB_TLS_CERT in case of web.https is enabled" }}
{{- end }}
  http: {{ getenv "DEX_WEB_HTTP" "0.0.0.0:5556" }}

{{- if getenv "DEX_TELEMETRY_HTTP" }}
telemetry:
  http: {{ .Env.DEX_TELEMETRY_HTTP }}
{{- end }}

expiry:
  deviceRequests: {{ getenv "DEX_EXPIRY_DEVICE_REQUESTS" "5m" }}
  signingKeys: {{ getenv "DEX_EXPIRY_SIGNING_KEYS" "6h" }}
  idTokens: {{ getenv "DEX_EXPIRY_ID_TOKENS" "24h" }}
  authRequests: {{ getenv "DEX_EXPIRY_AUTH_REQUESTS" "24h" }}

logger:
  level: {{ getenv "DEX_LOG_LEVEL" "info" }}
  format: {{ getenv "DEX_LOG_FORMAT" "text" }}

connectors:
- type: oidc
  id: okta
  name: okta
  config:
    issuer:  https://mydomain.okta.com
    clientID: okta client id
    clientSecret: okta client secret
    redirectURI: https://dex.example.com/callback
    scopes:
      - email
      - profile
      - openid
    claimMapping:
      email: emaial
      name: name
```

**Comment by elightcap** [comment]
ive actually made some progress, i think i just need to tweak my config to get everything working, hopefully will post a working config soon

**Comment by chaitanya-sistla** [comment]
Okay wonderful, I was wondering you were using azure entra. Also the dex URI and O2 URI are different.

**Comment by elightcap** [comment]
think im giving up for tonight, need some sleep to get fresh eyes.

ive got the sso button to come up, dex sends me to my upstream IDP and returns, but when it goes back to openobserve, /config/callback?code= 404s

**Comment by chaitanya-sistla** [comment]
Where are you adding the dex call back? Is it in the azure app?

**Comment by elightcap** [comment]
> Where are you adding the dex call back? Is it in the azure app?

i fixed it thanks to your blog actually.  The docs [here](https://openobserve.ai/docs/SSO/) say the redirect url should be /config/callback.  Your blog post shows /config/redirect. That is the proper URL. So i will post my working config below.

docker-compose.yml
```
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve-enterprise:latest
    container_name: openobserve
    restart: unless-stopped
    environment:
      enterprise: true
      O2_DEX_ENABLED: true
      O2_DEX_CLIENT_ID: "o2-client" # Client id of static client
      O2_DEX_CLIENT_SECRET: "base64 encoded value of client secret"   # This should be base64 encoded value of client secret 
      O2_DEX_BASE_URL: "https://dex.example.com/dex"    # URL of the Dex identity provider
      O2_DEX_REDIRECT_URL: "https://logs.example.com/config/redirect"    # Should match to redirect uri specified in dex
      O2_CALLBACK_URL: "https://logs.example.com/web/cb" # after sucessful token received from dex, user will be redirected to this page
      O2_DEX_SCOPES: "openid profile email groups offline_access"   # scopes to be fetched from dex
      O2_DEX_GROUP_ATTRIBUTE: "css"  # Maps user to OpenObserve organization.
      O2_DEX_ROLE_ATTRIBUTE: "cn"   # User's role in the organization.
      O2_DEX_DEFAULT_ORG: "default" # Default organization for users not belonging to any group in ldap
    ports:
      - "5080:5080"
    volumes:
      - data1:/data
  dex:
    image: dexidp/dex:latest
    container_name: dex
    restart: unless-stopped
    ports:
      - "5556:5556"
    volumes:
      - ./dex/config.docker.yaml:/etc/dex/config.docker.yaml
volumes:
  data1:
```

config.docker.yaml
```
issuer: https://dex.example.com/dex
staticClients:
    - id: o2-client
      secret: base64 encoded value of client secret
      name: o2-client
      redirectURIs:
        - 'https://logs.example.com/config/redirect'
oauth2:
  responseTypes:
  - code
  skipApprovalScreen: true

storage:
  type: sqlite3
  config:
    file: {{ getenv "DEX_STORAGE_SQLITE3_CONFIG_FILE" "/var/dex/dex.db" }}

web:
{{- if getenv "DEX_WEB_HTTPS" "" }}
  https: {{ .Env.DEX_WEB_HTTPS }}
  tlsKey: {{ getenv "DEX_WEB_TLS_KEY" | required "$DEX_WEB_TLS_KEY in case of web.https is enabled" }}
  tlsCert: {{ getenv "DEX_WEB_TLS_CERT" | required "$DEX_WEB_TLS_CERT in case of web.https is enabled" }}
{{- end }}
  http: {{ getenv "DEX_WEB_HTTP" "0.0.0.0:5556" }}

{{- if getenv "DEX_TELEMETRY_HTTP" }}
telemetry:
  http: {{ .Env.DEX_TELEMETRY_HTTP }}
{{- end }}

expiry:
  deviceRequests: {{ getenv "DEX_EXPIRY_DEVICE_REQUESTS" "5m" }}
  signingKeys: {{ getenv "DEX_EXPIRY_SIGNING_KEYS" "6h" }}
  idTokens: {{ getenv "DEX_EXPIRY_ID_TOKENS" "24h" }}
  authRequests: {{ getenv "DEX_EXPIRY_AUTH_REQUESTS" "24h" }}

logger:
  level: {{ getenv "DEX_LOG_LEVEL" "info" }}
  format: {{ getenv "DEX_LOG_FORMAT" "text" }}

connectors:
- type: oidc
  id: okta
  name: okta
  config:
    insecureSkipEmailVerified: true
    issuer:  https://mydomain.okta.com
    clientID: okta client id
    clientSecret: okta client secret
    redirectURI: https://dex.example.com/dex/callback
    scopes:
      - email
      - profile
      - openid
    claimMapping:
      email: email
      name: name
```

Then if someone wants to use a different upstream provider, they just change the connector in ` config.docker.yaml`
