### ISSUE TITLE
Intermittent Missing Traces for Specific Endpoints

### ISSUE THREAD

**Issue by sabith-nadakkavil** [openobserve/openobserve#5654]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

No

### Description

Facing an issue where traces for a few specific endpoints (/metadata, /Bundle, /Bundle/Validate) appear intermittently in OpenObserve. Logs for these endpoints are consistently visible, but traces are not reliably generated or exported.

**Context:**

- The mentioned endpoints are open and do not require authentication.
- Traces for other authenticated endpoints are generated and exported without issues.
- My tracing configuration in application.yml is as follows:

```
management:
  otlp:
    tracing:
      export:
        enabled: true
      endpoint: ${OPEN_OBSERVE_URL}/api/${ORG_NAME}/v1/traces
      headers:
        Authorization: Basic ${OPEN_OBSERVE_PASSWORD}
        organization: default
        stream-name: ${OPEN_OBSERVE_STREAM_NAME}-traces
      sampler:
        probability: 1.0
      service:
        name: default
```
**Observations:**

1. Traces for /metadata, /Bundle, and /Bundle/Validate appear randomly, suggesting that the instrumentation or exporter is not consistently capturing them.
2. These endpoints do not require authentication, unlike others that work reliably.

### Anything else?

**My Questions:**

1. Could the intermittent trace generation be related to these endpoints being open and bypassing authentication middleware?
2. Are there any known scenarios where OpenObserve or the OTLP exporter might skip capturing traces sporadically?
3. Is there a configuration I can tweak to ensure consistency?
