### ISSUE TITLE
SSO on single docker node

### ISSUE THREAD

**Issue by elightcap** [openobserve/openobserve#5713]
### Describe the problem that you experienced

Trying to setup SSO on a single docker node

### Enter the URL of the topic with the problem

https://openobserve.ai/docs/SSO

### Describe what you were looking for in the documentation

I am trying to enable SSO on a single docker node.

### Describe the actions that led you to experience the problem

I have set the listed env variables in a docker compose, i can see enterprise is enabled as i do have enterprise settings, however im not sure how to tell if openobserve is trying to call  dex on login.  I have also tried setting dex up to  run  in its own container.

### Describe what you want to experience that would fix the problem

Documentation on configuring dex with a single node.

### Provide any additional information here in as much as detail as you can

```true
Docker compose is as follows:

services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve-enterprise:latest
    container_name: openobserve
    restart: unless-stopped
    environment:
      enterprise.enabled: true
      enterprise.dex.enabled: true
      config.O2_DEX_CLIENT_ID: "my client id" # Client id of static client
      config.O2_DEX_CLIENT_SECRET: "base 64 encoded secret"   # This should be base64 encoded value of client secret 
      config.O2_DEX_BASE_URL: "https://dex.mydomain.com/dex"    # URL of the Dex identity provider
      config.O2_DEX_REDIRECT_URL: "https://logs.mydomain.com/config/callback"    # Should match to redirect uri specified in dex
      config.O2_CALLBACK_URL: "https://logs.mydomain.com/web/cb" # after sucessful token received from dex, user will be redirected to this page
      config.O2_DEX_SCOPES: "openid profile email groups offline_access"   # scopes to be fetched from dex
      config.O2_DEX_GROUP_ATTRIBUTE: "default"  # Maps user to OpenObserve organization.
      config.O2_DEX_ROLE_ATTRIBUTE: "cn"   # User's role in the organization.
      config.O2_DEX_DEFAULT_ORG: "default" # Default organization for users not belonging to any group in ldap
      enterprise.dex.config.issuer: "https://dex.mydomain.com"
      enterprise.dex.config.web.http: "0.0.0.5556"
      enterprise.dex.config.expiry.idTokens: "10m"
      enterprise.dex.config.expiry.refreshTokens.validIfNotUsedFor: "30m"
      enterprise.dex.config.staticClients.id: "o2-client"
      enterprise.dex.config.staticClients.redirectURIs: "https://logs.mydomain.com/config/callback"
      enterprise.dex.config.staticClients.name: "o2-client"
      enterprise.dex.config.staticClients.secret: "base64 encoded secret"
      enterprise.dex.config.oauth2.responseTypes: "code"
      enterprise.dex.config.oauth2.skipApprovalScreen: true
    ports:
      - "5080:5080"
    volumes:
      - data1:/data
  dex:
    image: dexidp/dex:latest
    container_name: dex
    restart: unless-stopped
    ports:
      - "5556:5556"
    volumes:
      - ./dex/config.docker.yaml:/etc/dex/config.docker.yaml
volumes:
  data1:

I have a seperate docker.config.yaml for dex connector settings.
```

**Comment by gaby** [comment]
@elightcap If you figure this out, please share. I also have a single-node. The official helm charts sets all of this, but it has too many containers.

I thought this required using https://github.com/openfga/openfga

**Comment by elightcap** [comment]
really there is no mention of openfga in the SSO config documentation.  i will keep trying things out to see though

**Comment by gaby** [comment]
> really there is no mention of openfga in the SSO config documentation. i will keep trying things out to see though

That's true it doesnt mention anything about it. Here are the vars: https://openobserve.ai/docs/environment-variables/#openfga

**Comment by elightcap** [comment]
Made some good progress

i have o2 going to dex. dex authenticates with my upstream IDP, which redirects to logs.example.com/config/callback, which unfortunately 404s

ill show you what i have so far though.

docker-compose.yml:
```
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve-enterprise:latest
    container_name: openobserve
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "root@example.com"
      ZO_ROOT_USER_PASSWORD: "a password"
      enterprise: true
      O2_DEX_ENABLED: true
      O2_DEX_CLIENT_ID: "o2-client" # Client id of static client
      O2_DEX_CLIENT_SECRET: "base64 encoded value of client secret "   # This should be base64 encoded value of client secret 
      O2_DEX_BASE_URL: "https://dex.example.com/dex"    # URL of the Dex identity provider
      O2_DEX_REDIRECT_URL: "https://logs.example.com/config/callback"    # Should match to redirect uri specified in dex
      O2_CALLBACK_URL: "https://logs.example.com/web/cb" # after sucessful token received from dex, user will be redirected to this page
      O2_DEX_SCOPES: "openid profile email groups offline_access"   # scopes to be fetched from dex
      O2_DEX_GROUP_ATTRIBUTE: "css"  # Maps user to OpenObserve organization.
      O2_DEX_ROLE_ATTRIBUTE: "cn"   # User's role in the organization.
      O2_DEX_DEFAULT_ORG: "default" # Default organization for users not belonging to any group in ldap
    ports:
      - "5080:5080"
    volumes:
      - data1:/data
  dex:
    image: dexidp/dex:latest
    container_name: dex
    restart: unless-stopped
    ports:
      - "5556:5556"
    volumes:
      - ./dex/config.docker.yaml:/etc/dex/config.docker.yaml
volumes:
  data1:
```

config.docker.yaml (this is mapped to the dex container about):
```
issuer: https://dex.example.com/dex
staticClients:
    - id: o2-client
      secret: dex client secret
      name: o2-client
      redirectURIs:
        - 'https://logs.example.com/config/callback'

oauth2:
  responseTypes:
  - code
  skipApprovalScreen: true

storage:
  type: sqlite3
  config:
    file: {{ getenv "DEX_STORAGE_SQLITE3_CONFIG_FILE" "/var/dex/dex.db" }}

web:
{{- if getenv "DEX_WEB_HTTPS" "" }}
  https: {{ .Env.DEX_WEB_HTTPS }}
  tlsKey: {{ getenv "DEX_WEB_TLS_KEY" | required "$DEX_WEB_TLS_KEY in case of web.https is enabled" }}
  tlsCert: {{ getenv "DEX_WEB_TLS_CERT" | required "$DEX_WEB_TLS_CERT in case of web.https is enabled" }}
{{- end }}
  http: {{ getenv "DEX_WEB_HTTP" "0.0.0.0:5556" }}

{{- if getenv "DEX_TELEMETRY_HTTP" }}
telemetry:
  http: {{ .Env.DEX_TELEMETRY_HTTP }}
{{- end }}

expiry:
  deviceRequests: {{ getenv "DEX_EXPIRY_DEVICE_REQUESTS" "5m" }}
  signingKeys: {{ getenv "DEX_EXPIRY_SIGNING_KEYS" "6h" }}
  idTokens: {{ getenv "DEX_EXPIRY_ID_TOKENS" "24h" }}
  authRequests: {{ getenv "DEX_EXPIRY_AUTH_REQUESTS" "24h" }}

logger:
  level: {{ getenv "DEX_LOG_LEVEL" "info" }}
  format: {{ getenv "DEX_LOG_FORMAT" "text" }}

connectors:
- type: oidc
  id: okta
  name: okta
  config:
    insecureSkipEmailVerified: true
    issuer:  https://myorg.okta.com
    clientID: okta client id
    clientSecret: okta client secret
    redirectURI: https://dex.example.com/dex/callback
    scopes:
      - email
      - profile
      - openid
    claimMapping:
      email: email
      name: name
```
