### ISSUE TITLE
thread '<unnamed>' panicked at /openobserve/src/service/db/user.rs:285:51

### ISSUE THREAD

**Issue by PixNyb** [openobserve/openobserve#5737]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Upon restarting my OpenObserve instance deployed with docker i get this error. OpenObserve has been running just fine before the issue started. This leads to me not being able to access the panel or collect metrics.

```yaml
  openobserve:
    container_name: openobserve
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 5080:5080
      - 5514:5514/tcp
      - 5514:5514/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - ZO_ROOT_USER_EMAIL=xxx
      - ZO_ROOT_USER_PASSWORD=xxx
      - ZO_SMTP_ENABLED=true
      - ZO_SMTP_HOST=xxx
      - ZO_SMTP_PORT=587
      - ZO_SMTP_USER_NAME=xxx
      - ZO_SMTP_PASSWORD=xxx
      - ZO_SMTP_REPLY_TO=xxx
      - ZO_SMTP_FROM_EMAIL=xxx
      - ZO_SMTP_ENCRYPTION=ssltls
      - ZO_META_STORE=mysql
      - ZO_META_MYSQL_DSN=mysql://xxx/openobserve?charset=utf8mb4
      - ZO_DATA_DIR=/data
      - ZO_USAGE_REPORTING_ENABLED=true
      - ZO_COMPACT_DATA_RETENTION_DAYS=14
      - ZO_WEB_URL=https://xxx
      - RUST_BACKTRACE=full
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./appdata/openobserve:/data
```

### Please provide the exception or error you saw

```true
openobserve      | 2025-01-19T09:06:24.086606784+00:00 INFO openobserve: System info: CPU cores 4, MEM total 7903 MB, Disk total 22252 GB, free 21347 GB    
openobserve      | 2025-01-19T09:06:24.089704252+00:00 INFO config::ider: init ider with machine_id: 0    
openobserve      | 2025-01-19T09:06:24.110893638+00:00 INFO infra::cache::file_data::disk: Loading disk cache start    
openobserve      | 2025-01-19T09:06:24.111628098+00:00 INFO infra::cache::file_data::disk: Loading disk cache done, total files: 0    
openobserve      | 2025-01-19T09:06:26.142865906+00:00 INFO sea_orm_migration::migrator: Applying 12 pending migrations
openobserve      | 2025-01-19T09:06:26.145346491+00:00 INFO sea_orm_migration::migrator: No pending migrations
openobserve      | 2025-01-19T09:06:26.146117427+00:00 INFO sea_orm_migration::migrator: Applying all pending migrations
openobserve      | 2025-01-19T09:06:26.148577636+00:00 INFO sea_orm_migration::migrator: No pending migrations
openobserve      | 2025-01-19T09:06:26.151362825+00:00 INFO openobserve::common::migration::dashboards: dashboard distinct values migration already done.    
openobserve      | thread '<unnamed>' panicked at /openobserve/src/service/db/user.rs:285:51:
openobserve      | called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)
openobserve      | stack backtrace:
openobserve      |    0:     0x7f902438585a - <unknown>
openobserve      |    1:     0x7f901f9a8593 - <unknown>
openobserve      |    2:     0x7f9024380c83 - <unknown>
openobserve      |    3:     0x7f90243856b2 - <unknown>
openobserve      |    4:     0x7f90243866a6 - <unknown>
openobserve      |    5:     0x7f90243864f0 - <unknown>
openobserve      |    6:     0x7f9024386c67 - <unknown>
openobserve      |    7:     0x7f9024386b0a - <unknown>
openobserve      |    8:     0x7f9024385d09 - <unknown>
openobserve      |    9:     0x7f90243867ac - <unknown>
openobserve      |   10:     0x7f901f9a5660 - <unknown>
openobserve      |   11:     0x7f901f9a5aa6 - <unknown>
openobserve      |   12:     0x7f9022e03e5f - <unknown>
openobserve      |   13:     0x7f902379d8f7 - <unknown>
openobserve      |   14:     0x7f9023192645 - <unknown>
openobserve      |   15:     0x7f90231d063b - <unknown>
openobserve      |   16:     0x7f902438ca0b - <unknown>
openobserve      | 2025-01-19T09:06:26.202233478+00:00 WARN ingester::wal: starting replay wal file: "/data/wal/logs/0/default/metadata/1737228162917560.wal"    
openobserve      | 2025-01-19T09:06:26.204684775+00:00 WARN ingester::wal: replay wal file: "/data/wal/logs/0/default/metadata/1737228162917560.wal", entries: 28, records: 32    
openobserve      | 2025-01-19T09:06:26.204755551+00:00 WARN ingester::wal: starting replay wal file: "/data/wal/logs/0/default/logs/1737205652429067.wal"    
openobserve      |   17:     0x7f9019bf31c4 - <unknown>
openobserve      |   18:     0x7f9019c72ac0 - __clone
openobserve      |   19:                0x0 - <unknown>
openobserve      | Error: backend job init failed: channel closed
openobserve      | 
openobserve      | Stack backtrace:
openobserve      |    0: <unknown>
openobserve      |    1: <unknown>
openobserve      |    2: <unknown>
openobserve      |    3: <unknown>
openobserve      |    4: <unknown>
openobserve      |    5: <unknown>
openobserve      |    6: <unknown>
openobserve      |    7: <unknown>
openobserve      |    8: __libc_start_main
openobserve      |    9: <unknown>
```

### Please provide the version you discovered this bug in (check about page for version information)

```true

```

**Comment by wlinna** [comment]
I'm getting this same error. I can't start OpenObserve anymore

**Comment by prabhatsharma** [comment]
Can you plz switch to postgres and confirm. We are deprecating MySQL.

**Comment by wlinna** [comment]
In my case it's not about MySQL. This is how openobserve looks like in my docker compose:

```
openobserve:
    image: public.ecr.aws/zinclabs/openobserve-enterprise:latest
    container_name: openobserve
    environment:
        - O2_AUDIT_ENABLED=true
        - ZO_DATA_DIR=/data
        - ZO_ROOT_USER_EMAIL=xyz   # Change to your desired email
        - ZO_ROOT_USER_PASSWORD=xyz2  # Change to a strong password

    volumes:
        - ./docker/volumes/openobserve-data:/data
    ports:
        - "5080:5080"
        - "5081:5081"

```

I haven't tested yet, but in my case the problem might be that I was previously using postgres for meta storage and GCS for data and then removed all that to try something.

**Comment by hengfeiyang** [comment]
Please let us know if you still have issues.

**Comment by wlinna** [comment]
I still have the same issue, yes

(version v0.14.6-rc8)

**Comment by hengfeiyang** [comment]
```
openobserve:
    image: public.ecr.aws/zinclabs/openobserve-enterprise:v0.14.7
    container_name: openobserve
    environment:
        - O2_AUDIT_ENABLED=true
        - ZO_DATA_DIR=/data
        - ZO_ROOT_USER_EMAIL=abc@abc.com   # Change to your desired email
        - ZO_ROOT_USER_PASSWORD=xyz2  # Change to a strong password

    volumes:
        - ./docker/volumes/openobserve-data:/data
    ports:
        - "5080:5080"
        - "5081:5081"
 ```
Please use a fixed version and try again, if you still have the issue, please share the error log, also maybe connect me and share you sqlite database, let's check the data. it looks you are using sqlite.

**Comment by wlinna** [comment]
Hello,
changing the version to v0.14.7 doesn't appear to change anything. Yes, the new version is in use according to Docker logs, but the problem remains. 

I probably should have said this earlier but I wanted to test myself first, but it turns out that so far I haven't got the time to verify this myself. Anyway, before I got this problem, I also tried some other configurations, namely:
1. For a time, I used s3 (for exploration purposes), instead of local docker volume, by configuring `ZO_LOCAL_MODE_STORAGE=s3` and the ` ZO_S3_*` family of env variables
2. In addition, I also temporarily used `ZO_META_STORE=postgres` and `ZO_META_POSTGRES_DSN=<my secret url>` 
3. Finally, I switched back to the configuration I posted earlier. This is when I noticed the problem for the first time. I didn't clear my old docker volume in-between

Here's the log:

```
2025-05-21T03:47:16.330698422+00:00 INFO openobserve: Starting OpenObserve v0.14.7    
2025-05-21T03:47:16.330788891+00:00 INFO openobserve: System info: CPU cores 4, MEM total 31.25 GB, Disk total 430.67 GB, free 97.80 GB    
2025-05-21T03:47:16.330802560+00:00 INFO openobserve: Caches info: Disk max size 12.22 GB, MEM max size 7.81 GB, Datafusion pool size: 11.72 GB    
2025-05-21T03:47:16.335074542+00:00 INFO config::ider: init ider with machine_id: 0    
2025-05-21T03:47:16.339599514+00:00 INFO openobserve::migration: DB_SCHEMA_VERSION match, skipping db upgrade    
2025-05-21T03:47:16.339881051+00:00 INFO infra::cache::file_data::disk: Loading disk cache start    
2025-05-21T03:47:16.340469310+00:00 INFO infra::cache::file_data::disk: Loading disk cache done, total files: 0    
2025-05-21T03:47:18.350740151+00:00 INFO o2_enterprise::enterprise::actions::action_manager: Action cluster URL is not set, skipping client initialization    
2025-05-21T03:47:18.350956036+00:00 INFO o2_enterprise::enterprise::pipeline::pipeline_file_server: [PipelineFileServer] started    
2025-05-21T03:47:18.351290498+00:00 INFO o2_enterprise::enterprise::pipeline::pipeline_file_server: [PipelineFileServer] PipelineWatcher started    
2025-05-21T03:47:18.351534316+00:00 INFO o2_enterprise::enterprise::pipeline::pipeline_file_server: [PipelineFileServer] running and waiting for shutdown signal    
2025-05-21T03:47:18.351646599+00:00 WARN o2_enterprise::enterprise::pipeline::pipeline_offset_manager: [PipelineOffsetManager] Recovered pipeline offset data from interrupted process.    
2025-05-21T03:47:18.354840127+00:00 INFO o2_enterprise::enterprise::pipeline::pipeline_watcher: [PipelineWatcher] init pipeline offset manager successfully    

thread '<unnamed>' panicked at /openobserve/src/service/db/user.rs:287:51:
called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: backend job init failed: channel closed
```

**Comment by hengfeiyang** [comment]
Can you try this CLI on any node:
```
./openobserve reset -c root
```

**Comment by wlinna** [comment]
How might I do that?

I'm running OpenObserve on Docker compose. When I try to attach to it with
`docker exec -it <id> sh`, I get 

> OCI runtime exec failed: exec failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown

I tried this before the container would restart:
```
docker exec -it <id> ./openobserve reset -c root
```

It didn't seem to do anything though. Maybe it didn't run anything. When I restart the container, I just get the same error as reported in my earlier message.

**Comment by hengfeiyang** [comment]
Okay, you use using Postgres right? can you run the SQL and share the data:
```sql
select  * from meta where module='user'
```

**Comment by wlinna** [comment]
I **was** using Postgres for a while, but like I said, I switched back to the config that I posted earlier, namely this:

```yaml
openobserve:
    image: public.ecr.aws/zinclabs/openobserve-enterprise:latest
    container_name: openobserve
    environment:
        - O2_AUDIT_ENABLED=true
        - ZO_DATA_DIR=/data
        - ZO_ROOT_USER_EMAIL=xyz   # Change to your desired email
        - ZO_ROOT_USER_PASSWORD=xyz2  # Change to a strong password

    volumes:
        - ./docker/volumes/openobserve-data:/data
    ports:
        - "5080:5080"
        - "5081:5081"
```

My postgres server has been offline since.

Later I changed the image to `public.ecr.aws/zinclabs/openobserve-enterprise:v0.14.7`
