### ISSUE TITLE
health check in docker compose causes the container to be unhealthy

### ISSUE THREAD

**Issue by ethan256** [openobserve/openobserve#6154]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Configuring a container health check in docker compose causes the container to be unhealthy. docker-compose.yml as follow:

```
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "root@example.com"
      ZO_ROOT_USER_PASSWORD: "Complexpass#123"
    ports:
      - "5080:5080"
    volumes:
      - data:/data
    healthcheck:
      test: curl -f http://localhost:5080/healthz
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
volumes:
  data:
```

result:
```
sudo docker ps
CONTAINER ID   IMAGE                                        COMMAND          CREATED         STATUS                     PORTS                                       NAMES
36eb44189c62   public.ecr.aws/zinclabs/openobserve:latest   "/openobserve"   2 minutes ago   Up 2 minutes (unhealthy)   0.0.0.0:5080->5080/tcp, :::5080->5080/tcp   openobserve
➜  ~ curl -f http://localhost:5080/healthz
{"status":"ok"}%
```

### Please provide the exception or error you saw

```true
sudo docker ps
CONTAINER ID   IMAGE                                        COMMAND          CREATED         STATUS                     PORTS                                       NAMES
36eb44189c62   public.ecr.aws/zinclabs/openobserve:latest   "/openobserve"   2 minutes ago   Up 2 minutes (unhealthy)   0.0.0.0:5080->5080/tcp, :::5080->5080/tcp   openobserve
```

### Please provide the version you discovered this bug in (check about page for version information)

```true

```
