### ISSUE TITLE
Health check

### ISSUE THREAD

**Issue by lloydchandran** [openobserve/openobserve#6561]
### Describe the problem that you experienced

I was trying to configure openobserve in docker compose. Not sure how I can create a health check. i want the otel collector to depend up on openobserve 

### Describe what you were looking for in the documentation

Would like to have a docker compose example with health check 

### If this problem caused an exception or error, please paste it here

```true

```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true

```

### Provide any additional information here in as much as detail as you can

```true

```

**Comment by hengfeiyang** [comment]
we have an API `http://localhost:5080/healthz` you can check it.

**Comment by pierrelemee** [comment]
Maybe I experience the same issue as @lloydchandran , when I try to run `openobserve` as Docker compose service

```yaml
name: "example"

services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      ZO_DATA_DIR: "/data"
      ZO_ROOT_USER_EMAIL: "root@example.com"
      ZO_ROOT_USER_PASSWORD: "Complexpass123"
    volumes:
      - ./.docker/openobserve/data:/data
    healthcheck:
      test: [ "CMD-SHELL", "curl", "--fail", "http://localhost:5080/healthz"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5080:5080"
```

The health check fails, while the application successfully started, because `curl` is not installed 

```sh
$ docker inspect --format "{{json .State.Health }}" example-openobserve-1 | jq
{
  "Status": "unhealthy",
  "FailingStreak": 6,
  "Log": [
    {
      "Start": "2026-01-29T09:46:04.799561467Z",
      "End": "2026-01-29T09:46:04.856083884Z",
      "ExitCode": -1,
      "Output": "OCI runtime exec failed: exec failed: unable to start container process: exec: \"curl\": executable file not found in $PATH"
or directory"
    },
```

In fact : I can't even open a shell to the created container, either `sh`, `bash` or `zsh`.

Maybe it could be helpful to document how to open a shell in a Docker container so it's possible to _extend_ the image with some handful CLI tools, like `curl` for health checking.
