### ISSUE TITLE
promql filter is applied only once

### ISSUE THREAD

**Issue by kabakaev** [openobserve/openobserve#6638]
### Which OpenObserve functionalities are the source of the bug?

metrics

### Is this a regression?

No

### Description

A metrics PromQL request returns invalid results when a query contains multiple filters. 
The first filter `{state="free"}` of the query given below is applied to all time-series.

```promql
system_filesystem_usage{state="free"} 
/ 
on(device,host_name)
(system_filesystem_usage{state="free"}+system_filesystem_usage{state="used"})
```

The expected result is a free disk space share, i.e. `free`/(`free`+`used`).

Instead, this query always returns `0.5`, which is `free`/(`free`+`free`).

The `system_filesystem_usage` metrics are ingested by [otelcol-contrib `hostmetrics` receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/README.md) configured in /etc/otel-config.yaml as:

```yaml
receivers:
  hostmetrics:
    root_path: /
    collection_interval: 30s
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:          
      processes:
processors:
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
  memory_limiter:
    check_interval: 5s
    limit_percentage: 75
    spike_limit_percentage: 15
  batch:
    send_batch_size: 10000
    timeout: 10s

extensions:
  zpages: {}

exporters:
  otlphttp/openobserve:
    endpoint: https://o2.example.com/api/default/
    headers:
      Authorization: "Basic changeme"
```

### Please provide the exception or error you saw

```true

```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.14.6-rc7
Commit Hash: aa10d42e01232a6cbbf307c4128500e98b475e37
Build Date: 2025-04-24T03:48:02Z
```
