### ISSUE TITLE
Enterprise version failed to start on docker restart

### ISSUE THREAD

**Issue by mjc0608** [openobserve/openobserve#6824]
### Which OpenObserve functionalities are the source of the bug?

login, home, Don't known / other

### Is this a regression?

No

### Description

Use docker for a local deploy. The first start successes and I can see the login page. Then, if I restart the container, the HTTP server would not start. No error found in log. Open source version does not have this issue.

Docker compose:
```
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve-enterprise:v0.14.7-debug
    environment:
      RUST_LOG: debug
      ZO_ROOT_USER_EMAIL: "i@jcma.me"
      ZO_ROOT_USER_PASSWORD: "Complexpass#123"
      ZO_WEB_URL: https://o2.it.jcma.me
    networks:
      - home_lab_network
    volumes:
      - data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.openobserve.loadbalancer.server.port=5080"
      - "traefik.http.services.openobserve.loadbalancer.server.scheme=http"
      - "traefik.http.routers.openobserve.rule=Host(`o2.it.jcma.me`)"
      - "traefik.http.routers.openobserve.tls.certresolver=letsencrypt"
      - "traefik.http.routers.openobserve.entrypoints=websecure"
      - "traefik.http.routers.openobserve.service=openobserve"
volumes:
  data:
networks:
  home_lab_network:
    external: true
```
Debug log attached below:
[o2-openobserve-1_logs.txt](https://github.com/user-attachments/files/20257236/o2-openobserve-1_logs.txt)

### Please provide a link to a minimal reproduction of the bug

See above. Place this file in a `compose.yaml` in a directory and run `docker compose up -d`, then `docker compose restart`.

### Please provide the exception or error you saw

No error in the log. Log attached above. Search "Starting OpenObserve" for the first and second start.

### Please provide the version you discovered this bug in (check about page for version information)

v0.14.7
