### ISSUE TITLE
No Role to select when creating user

### ISSUE THREAD

**Issue by kakalos12** [openobserve/openobserve#7053]
### Which OpenObserve functionalities are the source of the bug?

users

### Is this a regression?

Yes

### Description

Hi, 
i start up a brand new container but I can not add a user. because the role field is empty.  I'm using the self-host version of openobserve. 

<img width="1781" alt="Image" src="https://github.com/user-attachments/assets/ab960253-0fcd-4964-9d47-d5de68efee8c" />

Here is the docker compose file 

```
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.15.0-rc1
    container_name: openobserve
    volumes:
      - ./openobserve:/data
    environment:
      - ZO_ROOT_USER_EMAIL=admin@example.com
      - ZO_ROOT_USER_PASSWORD=admin

    restart: unless-stopped
    ports:
      - "5080:5080"


```

By the way, Just wanted to ask. I see the organization revamp pr was merged, is the feature for self-host version ? 

Thanks so much

### Please provide the exception or error you saw

```true

```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version : 0.15-rc1
```
