### ISSUE TITLE
SMTP Email Sending Fails with CryptoProvider Panic in Latest Docker Image

### ISSUE THREAD

**Issue by JesuisSidik** [openobserve/openobserve#7200]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

Yes

### Description

Bug Description

When trying to configure SMTP email alerts with the latest OpenObserve Docker image (`public.ecr.aws/zinclabs/openobserve:latest`), the server crashes with a panic error related to `CryptoProvider` from the `rustls` crate.

### Docker Setup

```yaml
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve
    restart: unless-stopped
    ports:
      - "5080:5080"
    environment:
      ZO_SMTP_ENABLED: "true"
      ZO_SMTP_HOST: "smtp.gmail.com"
      ZO_SMTP_PORT: "587"
      ZO_SMTP_USER_NAME: "myemail@gmail.com"
      ZO_SMTP_PASSWORD: "xxx xxx xxx"
      ZO_SMTP_FROM_EMAIL: "myemail@gmail.com"
      ZO_SMTP_ENCRYPTION: "starttls"
      ZO_SMTP_AUTH_MECHANISM: "plain"
      ZO_ROOT_USER_EMAIL: "root@example.com"
      ZO_ROOT_USER_PASSWORD: "12345678"
    volumes:
      - data:/data
volumes:
  data:




### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

```true
Error Log:

thread 'actix-server worker 5' panicked at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.20/src/crypto/mod.rs:249:14:
no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
latest
```
