### ISSUE TITLE
Missing Create Stream button

### ISSUE THREAD

**Issue by Orholt** [openobserve/openobserve#7337]
### Describe the problem that you experienced

![Image](https://github.com/user-attachments/assets/ab5e3261-010b-4055-a483-64b0dd23c50a)

I don't see Add Stream

About:
- Self hosted instance via docker compose:
```yaml
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "#EMAIL"
      ZO_ROOT_USER_PASSWORD: "#PASSWORD"
    ports:
      - "5080:5080"
    volumes:
      - data:/data
    networks:
      - openobserve
```

I also tested on other organizations - still nothing

Version: v0.15.0-rc2
Commit Hash: 529e520df82a6456e8b60cb62407ad79d3e504db
Build Date: 2025-06-11T04:11:25Z

![Image](https://github.com/user-attachments/assets/080b1286-da0c-487e-b6cf-3a7d7705fa34)

### Describe what you were looking for in the documentation

I looked into:
https://openobserve.ai/docs/user-guide/streams/streams-in-openobserve/#openobserve-cloud-or-the-enterprise-edition-with-role-based-access-control-rbac

I tried to create stream by following steps in docs

_"
Users with the required permissions can follow these steps to create streams:

- Select the organization from the top navigation bar.
- From the left navigation menu, select Streams.
- Click Add Stream.

"_

### If this problem caused an exception or error, please paste it here

```true

```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true

```

### Provide any additional information here in as much as detail as you can

```true
I was on root account

Version: v0.15.0-rc2
Commit Hash: 529e520df82a6456e8b60cb62407ad79d3e504db
Build Date: 2025-06-11T04:11:25Z
```
