### ISSUE TITLE
telegraf config file in toml format requires strings in double quotes

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#923]
### Which OpenObserve functionalities are the source of the bug?

metrics

### Is this a regression?

Yes

### Description

URL and authorization must be in double quotes

```toml
[[outputs.http]]
  ## URL is the address to send metrics to
  url = https://api.openobserve.ai/api/org1/prometheus/api/v1/write
  ## Data format to output.
  data_format = "prometheusremotewrite"

  [outputs.http.headers]
     Content-Type = "application/x-protobuf"
     Content-Encoding = "snappy"
     X-Prometheus-Remote-Write-Version = "0.1.0"
     Authorization = Basic hjdsfjsdgisdlfhdsl=
```
