### ISSUE TITLE
filebeat config error

### ISSUE THREAD

**Issue by perler** [openobserve/openobserve#940]
### Which OpenObserve functionalities are the source of the bug?

streams

### Is this a regression?

No

### Description

when using the generated filebeat.yml:
```
setup.ilm.enabled: false
setup.template.enabled: true
setup.template.name: "nginx-log"
setup.template.pattern: "nginx-log-*"
setup.template.overwrite: true

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log

output.elasticsearch:
  hosts: ["api.openobserve.ai"]
  timeout: 10
  path: "/api/pat_organization_****"
  index: {stream}
  username: "username@email.com"
  password: "**********"
```
I get: 
`Exiting: can not convert 'object' into 'string' accessing 'output.elasticsearch.index'`

what am I doing wrong here? I am using your test instance..

**Comment by omkarK06** [comment]
@perler In filebeat.yml ` index ` should be string. Replace ` {stream} ` with string.
For example
```
setup.ilm.enabled: false
setup.template.enabled: true
setup.template.name: "nginx-log"
setup.template.pattern: "nginx-log-*"
setup.template.overwrite: true

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log

output.elasticsearch:
  hosts: ["api.openobserve.ai"]
  timeout: 10
  path: "/api/pat_organization_****"
  index: "stream_name"
  username: "username@email.com"
  password: "**********"
  ```

**Comment by perler** [comment]
ok, this get's rid of errors, but I don't see any logs coming in:
```
setup.ilm.enabled: false
setup.template.enabled: true
setup.template.name: "log"
setup.template.pattern: "log"
setup.template.overwrite: true

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*log
    
output.elasticsearch:
  hosts: ["api.openobserve.ai"]
  timeout: 10
  path: "/api/pat_organization_xxx"
  index: "log"
  username: "user@email.com"
  password: "******"
```
![image](https://github.com/openobserve/openobserve/assets/623092/2f63710e-9c2d-4b19-b1f6-5dac60ae909a)
