### ISSUE TITLE
webui doesnt render

### ISSUE THREAD

**Issue by phixion** [openobserve/openobserve#951]
### Which OpenObserve functionalities are the source of the bug?

login, dashboards

### Is this a regression?

Yes

### Description

```yaml
networks:
  proxy:
    external: true
    name: proxy
services:
  openobserve:
    container_name: openobserve
    cpus: 0.25
    environment:
      ZO_PASSWORD: ${ZO_PASSWORD}
      ZO_USERNAME: ${ZO_USERNAME}
      ZO_DATA_DIR: /data
      ZO_ROOT_USER_EMAIL: ${ZO_ROOT_USER_EMAIL}
      ZO_ROOT_USER_PASSWORD: ${ZO_ROOT_USER_EMAIL}
    image: public.ecr.aws/zinclabs/openobserve:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.openobserve.entrypoints: https
      traefik.http.routers.openobserve.middlewares: chain-authelia@file
      traefik.http.routers.openobserve.rule: Host(`openobserve.${LOCAL_DOMAIN}`)
      traefik.http.routers.openobserve.service: openobserve
      traefik.http.routers.openobserve.tls: "true"
      traefik.http.routers.openobserve.tls.certresolver: cloudflare
      traefik.http.services.openobserve.loadbalancer.passhostheader: "true"
      traefik.http.services.openobserve.loadbalancer.server.port: '5080'
      traefik.http.services.openobserve.loadbalancer.sticky: "true"
    mem_limit: 4096m
    networks:
      - proxy
    ports:
    - protocol: tcp
      published: 5080
      target: 5080
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    volumes:
    - ./data:/data:rw
version: '3'
```

### Please provide the exception or error you saw

```true
services start fine. visiting the web-ui looks like this tho:
```
![](https://i.chaot.dev/5oXD.png)

### Please provide the version you discovered this bug in (check about page for version information)

```true
openobserve    | [2023-06-14T02:44:49Z INFO  openobserve] Starting OpenObserve v0.4.7
openobserve    | [2023-06-14T02:44:49Z INFO  openobserve::service::db::user] get; org_id=Some("default") name="monitoring@phixion.org"
openobserve    | [2023-06-14T02:44:49Z INFO  tracing::span] set;
openobserve    | [2023-06-14T02:44:49Z INFO  openobserve::service::db::user] Users Cached
openobserve    | [2023-06-14T02:44:49Z INFO  openobserve::service::db::user] Start watching user
openobserve    | [2023-06-14T02:44:49Z INFO  openobserve::service::db::functions] Start watching function
openobserve    | [2023-06-14T02:44:49Z INFO  openobserve::service::db::schema] Start watching stream schema
openobserve    | [2023-06-14T02:44:49Z INFO  openobserve::service::db::compact::delete] Start watching stream deleting
openobserve    | [2023-06-14T02:44:49Z INFO  openobserve::service::db::metrics] Start watching prometheus cluster leader
```
```


### Anything else?

.
